package com.gng.api.steps.ServiceOrdersSteps.SaveEnrollment;

public enum SaveEnrollmentApiLabel {

    save_enrollment,
    save_enrollment_mandatory,

    // Request ID Types
    EMPTY_REQUEST_ID,
    DUPLICATE_REQUEST_ID,
    SPECIAL_CHARS_REQUEST_ID,
    LONG_REQUEST_ID,
    UNICODE_CHARS_REQUEST_ID,

    //Invalid Customer Code Types
    MAX_LENGTH_CUSTOMER_CODE,
    NULL_CUSTOMER_CODE,
    DUPLICATE_CUSTOMER_CODE,
    SPECIAL_CHARS_CUSTOMER_CODE,
    //MAX_LENGTH_CUSTOMER_CODE,
    UNICODE_CHARS_CUSTOMER_CODE,


    // PremisesCode Types
    EMPTY_PREMISES_CODE,
    DUPLICATE_PREMISES_CODE,
    SPECIAL_CHARS_PREMISES_CODE,
    MAX_LENGTH_PREMISES_CODE,
    MIN_LENGTH_PREMISES_CODE,

    //Transaction ID Type
    MIN_LENGTH_TRANSACTION_ID,
    WHITESPACE_BETWEEN_TRANSACTION_ID,

    //transaction Type Cases
    EMPTY_TRANSACTION_TYPE,
    NUMERIC_TRANSACTION_TYPE,
    UPPERCASE_TRANSACTION_TYPE,
    ALPHANUMERIC_TRANSACTION_TYPE,
    LOWERCASE_TRANSACTION_TYPE,

    //plan Code
    NUMERIC_PLAN_CODE,
    SPECIAL_CHARS_PLAN_CODE,
    EMPTY_PLAN_CODE,
    UPPERCASE_PLAN_CODE,
    ALPHANUMERIC_PLAN_CODE,

    //LoginId
    MIN_LENGTH_LOGIN_ID,
    SPECIAL_CHARS_LOGIN_ID,
    EMPTY_LOGIN_ID,
    UPPERCASE_LOGIN_ID,
    ALPHANUMERIC_LOGIN_ID,
    MAX_LENGTH_LOGIN_ID,

    //enrollment Status
    MIN_LENGTH_ENROLLMENT_STATUS,
    SPECIAL_CHARS_ENROLLMENT_STATUS,
    EMPTY_ENROLLMENT_STATUS,
    LOWERCASE_ENROLLMENT_STATUS,
    ALPHANUMERIC_ENROLLMENT_STATUS,
    MAX_LENGTH_ENROLLMENT_STATUS,
    WHITESPACE_CONTAINS_ENROLLMENT_STATUS,

    //billing plan
    MAX_LENGTH_BILLING_PLAN,
    SPECIAL_CHARS_BILLING_PLAN,
    EMPTY_BILLING_PLAN,
    LOWERCASE_BILLING_PLAN,
}
