package com.gng.api.steps.ServiceOrdersSteps.SaveEnrollment;

public enum SaveEnrollmentApiLabel {

    save_enrollment,
    save_enrollment_mandatory,

    // Request ID Types
    EMPTY_REQUEST_ID,
    DUPLICATE_REQUEST_ID,
    SPECIAL_CHARS_REQUEST_ID,
    LONG_REQUEST_ID,
    UNICODE_CHARS_REQUEST_ID,

    //Invalid Customer Code Types
    MAX_LENGTH_CUSTOMER_CODE,
    NULL_CUSTOMER_CODE,
    DUPLICATE_CUSTOMER_CODE,
    SPECIAL_CHARS_CUSTOMER_CODE,
    //MAX_LENGTH_CUSTOMER_CODE,
    UNICODE_CHARS_CUSTOMER_CODE,


    // PremisesCode Types
    EMPTY_PREMISES_CODE,
    DUPLICATE_PREMISES_CODE,
    SPECIAL_CHARS_PREMISES_CODE,
    MAX_LENGTH_PREMISES_CODE,
    MIN_LENGTH_PREMISES_CODE,

    //Transaction ID Type
    MIN_LENGTH_TRANSACTION_ID,
    WHITESPACE_BETWEEN_TRANSACTION_ID,

    //transaction Type Cases
    EMPTY_TRANSACTION_TYPE,
    NULL_TRANSACTION_TYPE,
    NUMERIC_TRANSACTION_TYPE,
    UPPERCASE_TRANSACTION_TYPE,
    ALPHANUMERIC_TRANSACTION_TYPE,
    LOWERCASE_TRANSACTION_TYPE,

}
