package com.gng.api.steps.turnOff.AccountsApiSteps.SearchAccounts;

public enum SearchAccountsTOffApiLabel {

    search_accounts,
    search_accounts_mandatory,
    RESIDENTIAL_VALID_ACTIVE_ACCOUNT_TC75,
    COMMERCIAL_VALID_ACTIVE_ACCOUNT_TC76,
    INVALID_COMBINATION_OF_LASTNAME_ZIPCODE_TC77,
    VALID_COMBINATION_OF_LASTNAME_ZIPCODE_TC78,
    RESIDENTIAL_VALID_ACTIVE_ACCOUNT_TC79,
    SENIOR_RESIDENTIAL_VALID_ACTIVE_ACCOUNT_TC80,
    COMMERCIAL_VALID_ACTIVE_PASTDUEBALANCE_ACCOUNT_TC81,
    COMMERCIAL_VALID_ACTIVE_SONP_ACCOUNT_TC82,

    //Positive test conditions for Customer and Premises code search parameters
    ACTIVE_RS_NEW_NON_METERED_TC_56,
    ACTIVE_MSB_ACCOUNT_TC_57,
    ACTIVE_RS_NEW_NON_METERED_TC_58,
    INACTIVE_RS_METERED_TC_59,
    INACTIVE_BAD_DEBT_BALANCE_TC_60,
    RS_INACTIVE_WITH_SONP_TC_61,
    RS_INACTIVE_NON_METER_TC_62,
    RS_NEW_BANKRUPCY_TC_63,
    RS_INACTIVE_BANKRUPCY_TC_64,
    CM_NEW_NON_METERED_TC_65,
    CM_ACTIVE_NON_METERED_TC_67,
    CM_INACTIVE_METERED_TC_68,
    CM_INACTIVE_BAD_DEBT_TC_69,
    CM_INACTIVE_SONP_TC_70,
    CM_INACTIVE_NON_METERED_TC_71,
    CM_NEW_BANKRUPCY_TC_72,
    CM_INACTIVE_BANKRUPCY_TC_73,
    VALID_CUST_CODE_INVALID_PREM_CODE_TC_74,
    RS_ACTIVE_ACCOUNT_TC_75,
    CM_ACTIVE_ACCOUNT_TC_76


}
