package com.gng.api.steps.turnOff.AccountsApiSteps.SearchAccounts;

public enum SearchAccountsTOffApiLabel {

    search_accounts,
    search_accounts_mandatory,
    RESIDENTIAL_VALID_ACTIVE_ACCOUNT_TC75,
    COMMERCIAL_VALID_ACTIVE_ACCOUNT_TC76,
    INVALID_COMBINATION_OF_LASTNAME_ZIPCODE_TC77,
    VALID_COMBINATION_OF_LASTNAME_ZIPCODE_TC78,
    RESIDENTIAL_VALID_ACTIVE_ACCOUNT_TC79,
    SENIOR_RESIDENTIAL_VALID_ACTIVE_ACCOUNT_TC80,
    COMMERCIAL_VALID_ACTIVE_PASTDUEBALANCE_ACCOUNT_TC81,
    COMMERCIAL_VALID_ACTIVE_SONP_ACCOUNT_TC82,
    COMMERCIAL_VALID_ACTIVE_PENDING_REWARDS_TC83,
    COMMERCIAL_VALID_ACTIVE_ETC_TC_85,
    COMMERCIAL_VALID_ACTIVE_NO_ETC_TC_86,
    COMMERCIAL_VALID_ACTIVE_PRICE_PLAN_CCV_TC_87,
    COMMERCIAL_VALID_FINAL_ACCOUNT_TC_88,

    //Positive test conditions for Customer and Premises code search parameters
    ACTIVE_RS_NEW_NON_METERED_TC_56,
    ACTIVE_MSB_ACCOUNT_TC_57,
    ACTIVE_RS_NEW_NON_METERED_TC_58,
    INACTIVE_RS_METERED_TC_59,
    INACTIVE_BAD_DEBT_BALANCE_TC_60,
    RS_INACTIVE_WITH_SONP_TC_61,
    RS_INACTIVE_NON_METER_TC_62,
    RS_NEW_BANKRUPCY_TC_63,
    RS_INACTIVE_BANKRUPCY_TC_64,
    CM_NEW_NON_METERED_TC_65,
    CM_ACTIVE_NON_METERED_TC_67,
    CM_INACTIVE_METERED_TC_68,
    CM_INACTIVE_BAD_DEBT_TC_69,
    CM_INACTIVE_SONP_TC_70,
    CM_INACTIVE_NON_METERED_TC_71,
    CM_NEW_BANKRUPCY_TC_72,
    CM_INACTIVE_BANKRUPCY_TC_73,
    VALID_CUST_CODE_INVALID_PREM_CODE_TC_74,
    RS_ACTIVE_ACCOUNT_TC_75,
    CM_ACTIVE_ACCOUNT_TC_76,
    RS_ACTIVE_SONP_NON_MASTER_TC_91,
    RS_ACTIVE_PENDING_REWARDS_TC_92,
    RS_ACTIVE_UNAPPLIED_DEPOSIT_TC_93,
    RS_ACTIVE_NO_UNAPPLIED_DEPOSIT_TC_94,
    RS_ACTIVE_PGB_PRICE_PLAN_EXP_DATE_TC_95,
    RS_ACTIVE_MKT_PRICE_PLAN_NO_EXP_DATE_TC_96,
    RS_ACTIVE_ETC_TC_97,
    RS_ACTIVE_ETC_RGB_PRICE_PLAN_TC_98,
    RS_ACTIVE_GREENER_LIFE_TC_99,
    RS_ACTIVE_CSV_PRICE_PLAN_TC_100,
    RS_FINAL_ACCOUNT_TC_101,
    RS_ACTIVE_ACCOUNT_TC_102,
    SSP_ACCOUNT_WITH_ETC_TC_105A,
    SSP_ACCOUNT_WITHOUT_ETC_105B,
    NON_SSP_ACCOUNT_WITH_ETC_105C,
    NON_SSP_ACCOUNT_WITHOUT_ETC_105D,


    //positive test conditions related to premises parameters
    ALL_PREMISES_FIELDS_TC_104,
    PREMISES_STREET_NAME_CITY_STATE_ZIP_TC_105


}
