package com.gng.api.steps.UsersApiSteps.ResetPassword;

public enum ResetPasswordApiLabel {

    reset_password,
    reset_password_mandatory,

    //requestID
    WITHOUT_REQUEST_ID_TC21,
    NULL_REQUEST_ID_TC21A,
    DUPLICATE_REQUEST_ID_TC22,
    LONG_REQUEST_ID_TC23,


    //loginId
    WITHOUT_LOGIN_ID_AND_OLD_PASSWORD_TC24,
    NULL_LOGIN_ID_AND_OLD_PASSWORD_TC24A,
    WITHOUT_LOGIN_ID_TC25,
    NULL_LOGIN_ID_TC25A,
    MAX_LENGTH_LOGIN_ID_TC26,
    SPECIAL_CHAR_LOGIN_ID_TC27,
    INVALID_LOGIN_ID_NOT_IN_USER_TABLE_TC28,

    //oldPassword
    NULL_OLD_PASSWORD_TC29,
    INVALID_OLD_PASSWORD_FORMAT_NOT_ENCRYPTED_TC30,
    INVALID_OLD_PASSWORD_FORMAT_ENCRYPTED_MAX_CHAR_TC31,
    INVALID_PASSWORD_FORMAT_ENCRYPTED_MIN_7_CHAR_TC31_1,




    //newPassword
    NULL_NEW_PASSWORD_TC32,
    INVALID_NEW_PASSWORD_FORMAT_NOT_ENCRYPTED_TC33,
    INVALID_NEW_PASSWORD_FORMAT_ENCRYPTED_MAX_CHAR_TC34,
    INVALID_PASSWORD_FORMAT_ENCRYPTED_MIN_7_CHAR_TC34_1,
    OLD_PASSWORD_NEW_PASSWORD_SAME_TC35,

}
