package com.gng.api.steps.turnOn.ServiceOrdersSteps.GetPrepayPlanRequote;

public enum GetPrepayPlansRequoteApiLabel {

    get_prepay_plans_requote,
    get_prepay_plans_requote_mandatory,

    // positive test conditions
    GET_PREPAY_PLANS_REQUOTE_POSITIVE_TC_456,
    GET_PREPAY_PLANS_REQUOTE_POSITIVE_TC_471,
    GET_PREPAY_PLANS_REQUOTE_POSITIVE_TC_472,
    GET_PREPAY_PLANS_REQUOTE_AND_OFFERS_SAVE_ENROLLMENT_PREV_SAVED_TC_429,
    GET_PREPAY_PLANS_REQUOTE_AND_OFFERS_SAVE_ENROLLMENT_PREV_SAVED_TC_430,
    GET_PREPAY_PLANS_REQUOTE_AND_OFFERS_SAVE_ENROLLMENT_PREV_SAVED_TC_448,
    GET_PREPAY_PLANS_REQUOTE_AND_OFFERS_SAVE_ENROLLMENT_PREV_SAVED_TC_449,


    //negative test conditions
    GET_PREPAY_PLANS_REQUOTE_NEGATIVE_TC_456,
    GET_PREPAY_PLANS_REQUOTE_NEGATIVE_TC_457,
    GET_PREPAY_PLANS_REQUOTE_NEGATIVE_TC_458,
    GET_PREPAY_PLANS_REQUOTE_NEGATIVE_TC_459,
    GET_PREPAY_PLANS_REQUOTE_NEGATIVE_TC_460,
    GET_PREPAY_PLANS_REQUOTE_NEGATIVE_TC_461,
    GET_PREPAY_PLANS_REQUOTE_NEGATIVE_TC_462,
    GET_PREPAY_PLANS_REQUOTE_NEGATIVE_TC_463,
    GET_PREPAY_PLANS_REQUOTE_NEGATIVE_TC_464,
    GET_PREPAY_PLANS_REQUOTE_NEGATIVE_TC_465,
    GET_PREPAY_PLANS_REQUOTE_NEGATIVE_TC_466,
    GET_PREPAY_PLANS_REQUOTE_NEGATIVE_TC_467,
    GET_PREPAY_PLANS_REQUOTE_NEGATIVE_TC_468,
    GET_PREPAY_PLANS_REQUOTE_NEGATIVE_TC_469,
    GET_PREPAY_PLANS_REQUOTE_EXISTING_QUOTE_NOT_EXPIRED_NEGATIVE_TC_470,
    GET_PREPAY_PLANS_REQUOTE_PRP_ENROLLED_NEGATIVE_TC_471
}
