Feature: Verify SearchAccounts ServiceTransfer Api

  Background: Generate Authentication Token
    When a request is made to generate authentication token
    Then verify Authentication Token Api response status code is 200
    And a valid token is received in response


  @SearchAccountsServiceTransfer @Phase1 @NegativeFlow
  Scenario Outline: SearchAccountsApiServiceTransfer Api - Verify the "<testCondition>" for searchAccounts API
    When a request is made to the SearchAccounts Api for "<testCondition>"
    Then verify response code of "SearchAccounts" Api is 200
    And response should have ErrorCode <errorCode> and ErrorMessage "<errorMessage>"

    Examples:
      | testCondition                                          | errorCode | errorMessage                                                                                                                                                                     |
      | NO_SEARCH_PARAMETERS_PROVIDED_TC_1                     | 10116     | At least one of the following is required: GNG Account Number, Business Name, First and Last Name (with Zip Code), Social Security Number, AGLC Account Number or Premise Address.|
      | MISSING_REQUEST_ID_TC_2                                | 10001     | Missing Request ID                                                                                                                                                                |
      | INVALID_REQUEST_ID_LENGTH_TC_3                         | 10002     | Invalid Request ID                                                                                                                                                                |
      | DUPLICATE_REQUEST_ID_TC_4                              | 10003     | Duplicate Request ID                                                                                                                                                              |
      | MISSING_LOGIN_ID_TC_5                                  | 10112     | Invalid or missing Login ID                                                                                                                                                       |
      | INVALID_LOGIN_ID_LENGTH_TC_6                           | 10112     | Invalid or missing Login ID                                                                                                                                                       |
      | INVALID_LOGIN_ID_FORMAT_TC_7                           | 10112     | Invalid or missing Login ID                                                                                                                                                       |
      | INVALID_LOGIN_ID_TC_8                                  | 2000      | Invalid Login ID                                                                                                                                                                  |
      | MISSING_CUSTOMER_CODE_TC_9                             | 1001      | Invalid Request: Invalid required search field combination - customerCode required.                                                                                               |
      | MISSING_PREMISES_CODE_TC_10                            | 1001      | Invalid Request: Invalid required search field combination - premisesCode required.                                                                                               |
      | INVALID_CUSTOMER_CODE_LENGTH_TC_11                     | 10115     | Invalid search parameter(s)                                                                                                                                                       |
      | INVALID_PREMISES_CODE_LENGTH_TC_12                     | 10115     | Invalid search parameter(s)                                                                                                                                                       |
      | MISSING_TRANSACTION_TYPE_TC_13                         | 10113     | Invalid or missing Transaction Type                                                                                                                                               |
      | INVALID_TRANSACTION_TYPE_TC_14                         | 10113     | Invalid or missing Transaction Type                                                                                                                                               |
      | INVALID_TRANSACTION_TYPE_LENGTH_TC_15                  | 10113     | Invalid or missing Transaction Type                                                                                                                                               |
      | INVALID_BUSINESS_NAME_LENGTH_TC_16                     | 10115     | Invalid search parameter(s)                                                                                                                                                       |
      | INVALID_CUSTOMER_LAST_NAME_LENGTH_TC_17                | 10115     | Invalid search parameter(s)                                                                                                                                                       |
      | MISSING_PREMISES_ZIP_CODE_TC_19                        | 1001      | Invalid Request: Invalid required search field combination - premisesZipCode required.                                                                                            |
      | MISSING_TRANSACTION_TYPE_TC_20                         | 10113     | Invalid or missing Transaction Type                                                                                                                                               |
      | INVALID_FIRST_NAME_LENGTH_TC_21                        | 10115     | Invalid search parameter(s)                                                                                                                                                       |
      | UNENCRYPTED_SSN_TC_22                                  | 10115     | Invalid search parameter(s)                                                                                                                                                       |
      | INVALID_SSN_LENGTH_TC_23                               | 10115     | Invalid search parameter(s)                                                                                                                                                       |
      | TAX_ID_NOT_ALLOWED_TC_24                               | 2200      | Parameter Value should be null-Federal Tax ID                                                                                                                                     |
      | SSN_AND_TAX_ID_PROVIDED_TC_25                          | 2200      | Parameter Value should be null-Federal Tax ID                                                                                                                                     |
      | PHONE_NOT_ALLOWED_TC_26                                | 2200      | Parameter Value should be null-Phone Number                                                                                                                                       |
      | INVALID_AGLC_ACCOUNT_NO_LENGTH_TC_27                   | 10115     | Invalid search parameter(s)                                                                                                                                                       |
      | NON_NUMERIC_AGLC_ACCOUNT_NO_TC_28                      | 10115     | Invalid search parameter(s)                                                                                                                                                       |
      | INVALID_STREET_NUMBER_LENGTH_TC_29                     | 10115     | Invalid search parameter(s)                                                                                                                                                       |
      | INVALID_STREET_PRE_DIR_LENGTH_TC_30                    | 10115     | Invalid search parameter(s)                                                                                                                                                       |
      | INVALID_STREET_NAME_LENGTH_TC_31                       | 10115     | Invalid search parameter(s)                                                                                                                                                       |
      | MISSING_PREMISES_STREET_NAME_TC_32                     | 1001      | Invalid Request: Invalid required search field combination - premisesStreetName required.                                                                                         |
      | INVALID_STREET_SUFFIX_LENGTH_TC_33                     | 10115     | Invalid search parameter(s)                                                                                                                                                       |
      | INVALID_PREMISES_STREET_POST_DIRECTION_LENGTH_TC_34    | 10115     | Invalid search parameter(s)                                                                                                                                                       |
      | INVALID_UNIT_TYPE_LENGTH_TC_35                         | 10115     | Invalid search parameter(s)                                                                                                                                                       |
      | PREMISES_UNIT_TYPE_MISSING_TC_36                       | 1001      | Invalid Request: Invalid required search field combination - premisesUnitType required.                                                                                           |
      | INVALID_PREMISES_UNIT_NUMBER_FORMAT_TC_37              | 10115     | Invalid search parameter(s)                                                                                                                                                       |
      | MISSING_UNIT_NUMBER_TC_38                              | 1001      | Invalid Request: Invalid required search field combination - premisesUnitNumber required.                                                                                         |
      | INVALID_PREMISES_CITY_LENGTH_TC_39                     | 10115     | Invalid search parameter(s)                                                                                                                                                       |
      | MISSING_PREMISES_CITY_TC_40                            | 1001      | Invalid Request: Invalid required search field combination - premisesCity required.                                                                                               |
      | INVALID_STATE_CODE_LENGTH_TC_41                        | 10115     | Invalid PremisesStateCode provided                                                                                                                                                |
      | MISSING_STATE_CODE_TC_42                               | 1001      | Invalid Request: Invalid required search field combination - premisesStateCode required.                                                                                          |
      | INVALID_ZIP_CODE_LENGTH_TC_43                          | 10115     | Invalid PremisesZipCode provided                                                                                                                                                  |
      | INVALID_ZIP_CODE_LENGTH_LESS_THAN_5_TC_44              | 10115     | Invalid PremisesZipCode provided                                                                                                                                                  |
      | MISSING_ZIP_CODE_TC_45                                 | 1001      | Invalid Request: Invalid required search field combination - premisesZipCode required.                                                                                            |