package com.gng.api.steps.UsersApiSteps.GetUserRoles;

public enum GetUserRolesApiLabel {


    get_user_roles,
    get_user_roles_mandatory,


    //requestID
    NULL_REQUEST_ID_TC3,
    NO_REQUEST_ID_TC3A,
    DUPLICATE_REQUEST_ID_TC4,
    LONG_REQUEST_ID_TC5,

    //LoginID
    WITHOUT_LOGIN_ID_AND_PASSWORD_TC6,
    NULL_LOGIN_ID_AND_PASSWORD_TC6A,
    WITHOUT_LOGIN_ID_TC7,
    NULL_LOGIN_ID_TC7A,
    LOGIN_ID_WITH_SPECIAL_CHAR_TC9,
    LOGIN_ID_MORE_THAN_30_CHAR_TC8,



    //password
    NULL_PASSWORD_TC10,
    INVALID_PASSWORD_FORMAT_NOT_ENCRYPTED_TC11,
    INVALID_PASSWORD_FORMAT_ENCRYPTED_10_CHAR_TC12,
    INVALID_PASSWORD_FORMAT_ENCRYPTED_7_CHAR_TC12_1,

    //testCondition
    INVALID_LOGIN_ID_TC13,
    PASSWORD_MISMATCH_WITH_LOGIN_ID_TC14,
    PASSWORD_MISMATCH_WITH_LOGIN_ID_LOCK_TC15,
    EXPIRED_PASSWORD_TC16,
    LOCKED_LOGIN_ID_TC17,

}
