package com.gng.api.steps.poc.GetAccountInfo;

public enum GetAccountInfoApiLabel {
    get_account_info,

    MISSING_REQUEST_ID_NEGATIVE_TC15,
    DUPLICATE_REQUEST_ID_NEGATIVE_TC16,
    MISSING_CUSTOMER_CODE_NEGATIVE_TC17,
    MISSING_PREMISES_CODE_NEGATIVE_TC18,
    INVALID_CUSTOMER_CODE_LENGTH_NEGATIVE_TC19,
    INVALID_PREMISES_CODE_LENGTH_NEGATIVE_TC20,
    INVALID_ACCOUNT_COMBINATION_NEGATIVE_TC21,
    ACTIVE_WITH_PA_PAST_DUE_POSITIVE_TC22,
    INACTIVE_WITH_RECURRING_CC_POSITIVE_TC23,
    FINAL_WITH_ABD_POSITIVE_TC24,
    ACTIVE_DEFAULTED_PA_WITH_BUDGET_POSITIVE_TC25,
    INACTIVE_BAD_DEBT_SONP_DISCLETTERS_POSITIVE_TC26,
    NEW_NO_BILLS_YET_POSITIVE_TC27
}
