package com.gng.api.steps.ServiceOrdersSteps.GetEligiblePlansAndOffers;

public enum GetEligiblePlansAndOffersApiLabel {


    get_eligible_plans_and_offers,
    get_eligible_plans_and_offers_mandatory,

    //request ID
    EMPTY_REQUEST_ID,
    DUPLICATE_REQUEST_ID,
    SPECIAL_CHARS_REQUEST_ID,
    LONG_REQUEST_ID,
    UNICODE_CHARS_REQUEST_ID,

    //login ID
    MIN_LENGTH_LOGIN_ID,
    SPECIAL_CHARS_LOGIN_ID,
    EMPTY_LOGIN_ID,
    UPPERCASE_LOGIN_ID,
    ALPHANUMERIC_LOGIN_ID,
    MAX_LENGTH_LOGIN_ID,

    //transaction type
    EMPTY_TRANSACTION_TYPE,
    NUMERIC_TRANSACTION_TYPE,
    UPPERCASE_TRANSACTION_TYPE,
    LOWERCASE_TRANSACTION_TYPE,
    ALPHANUMERIC_TRANSACTION_TYPE,
    WHITESPACE_CONTAINS_TRANSACTION_TYPE,
    MAX_LENGTH_TRANSACTION_TYPE,

    //customer Type
    EMPTY_CUSTOMER_TYPE,
    MIN_LENGTH_CUSTOMER_TYPE,
    NUMERIC_CUSTOMER_TYPE ,
    SPL_CHAR_CUSTOMER_TYPE,
    MAX_LENGTH_CUSTOMER_TYPE,

    //enrollment Sources
    EMPTY_ENROLLMENT_SOURCES,
    NUMERIC_ENROLLMENT_SOURCES,
    SPL_CHAR_ENROLLMENT_SOURCES,
    MAX_LENGTH_ENROLLMENT_SOURCES,

    //customer last name
    EMPTY_CUSTOMER_LAST_NAME,
    LOWERCASE_CUSTOMER_LAST_NAME,
    SPL_CHAR_CUSTOMER_LAST_NAME,
    MAX_LENGTH_CUSTOMER_LAST_NAME,
    NUMERIC_CUSTOMER_LAST_NAME,


}
