package com.gng.api.steps.ServiceOrdersSteps.GetEligiblePlansAndOffers;

public enum GetEligiblePlansAndOffersApiLabel {


    get_eligible_plans_and_offers,
    get_eligible_plans_and_offers_mandatory,

    //request ID
    EMPTY_REQUEST_ID,
    DUPLICATE_REQUEST_ID,
    SPECIAL_CHARS_REQUEST_ID,
    LONG_REQUEST_ID,
    UNICODE_CHARS_REQUEST_ID,

    //login ID
    MIN_LENGTH_LOGIN_ID,
    SPECIAL_CHARS_LOGIN_ID,
    EMPTY_LOGIN_ID,
    UPPERCASE_LOGIN_ID,
    ALPHANUMERIC_LOGIN_ID,
    MAX_LENGTH_LOGIN_ID,

    //transaction type
    EMPTY_TRANSACTION_TYPE,
    NUMERIC_TRANSACTION_TYPE,
    UPPERCASE_TRANSACTION_TYPE,
    LOWERCASE_TRANSACTION_TYPE,
    ALPHANUMERIC_TRANSACTION_TYPE,
    WHITESPACE_CONTAINS_TRANSACTION_TYPE,
    MAX_LENGTH_TRANSACTION_TYPE,

    //customer Type
    EMPTY_CUSTOMER_TYPE,
    MIN_LENGTH_CUSTOMER_TYPE,
    NUMERIC_CUSTOMER_TYPE,
    SPL_CHAR_CUSTOMER_TYPE,
    MAX_LENGTH_CUSTOMER_TYPE,

    //enrollment Sources
    EMPTY_ENROLLMENT_SOURCES,
    NUMERIC_ENROLLMENT_SOURCES,
    SPL_CHAR_ENROLLMENT_SOURCES,
    MAX_LENGTH_ENROLLMENT_SOURCES,

    //customer last name
    EMPTY_CUSTOMER_LAST_NAME,
    LOWERCASE_CUSTOMER_LAST_NAME,
    SPL_CHAR_CUSTOMER_LAST_NAME,
    MAX_LENGTH_CUSTOMER_LAST_NAME,
    NUMERIC_CUSTOMER_LAST_NAME,

    //customer first name
    EMPTY_CUSTOMER_FIRST_NAME,

    //seasonalSavingsProgramIndicator
    NULL_SEASONAL_SAVINGS_PROGRAM_INDICATOR,

    //premises street name
    EMPTY_PREMISES_STREET_NAME,
    SPL_CHAR_PREMISES_STREET_NAME,
    MAX_LENGTH_PREMISES_STREET_NAME,


    //credit check
    EMPTY_CREDIT_CHECK_OPTION,
    SPL_CHAR_CREDIT_CHECK_OPTION,
    MAX_LENGTH_CREDIT_CHECK_OPTION,
    NUMERIC_CREDIT_CHECK_OPTION,
    ALPHANUMERIC_CREDIT_CHECK_OPTION,

    //TenantLandlord
    EMPTY_TENANT_LANDLORD,
    SPL_CHAR_TENANT_LANDLORD,
    MAX_LENGTH_TENANT_LANDLORD,
    LOWERCASE_TENANT_LANDLORD,
    NUMERIC_TENANT_LANDLORD,


    //AcnStatusIndicator
    EMPTY_ACN_STATUS_INDICATOR,
    SPL_CHAR_ACN_STATUS_INDICATOR,
    MAX_LENGTH_ACN_STATUS_INDICATOR,
    ALPHANUMERIC_ACN_STATUS_INDICATOR,

    //testCondition
    NULL_AUTHORIZED_BY,

    //referralCode
    MAX_REFERRAL_CODE,
    NONNUMERIC_REFERRAL_CODE,
    ALPHANUMERIC_REFERRAL_CODE,
    VALID_REFERRAL_CODE_WITH_MISSING_MARKETING_CODE,

    //PremisesStreetNumber
    MAX_PREMISES_STREET_NUMBER,

    //premisesStreetPreDirection
    MAX_PREMISES_STREET_PRE_DIRECTION,
    INVALID_PREMISES_STREET_PRE_DIRECTION_EQUAL_TO_TWO,

    MAX_PREMISES_STREET_NAME,
    NULL_PREMISES_STREET_NAME,
    //PremisesStreetSuffix
    MAX_PREMISES_STREET_SUFFIX,
    INVALID_PREMISES_STREET_SUFFIX,

    //PremisesStreetPostDirection
    MAX_PREMISES_STREET_POST_DIRECTION,
    INVALID_PREMISES_STREET_POST_DIRECTION_EQUAL_TO_TWO,

    //premisesUnitType
    MAX_PREMISES_UNIT_TYPE,
    INVALID_PREMISES_UNIT_TYPE,

    //premisesUnitNumber
    MAX_PREMISES_UNIT_NUMBER,

    //premisesCity
    MAX_PREMISES_CITY,
    NULL_PREMISES_CITY,

    //premises state code
    EMPTY_PREMISES_STATE_CODE,
    MAX_LENGTH_PREMISES_STATE_CODE,
    INVALID_PREMISES_STATE_CODE_EQUAL_TO_TWO,

    //premises zip code
    EMPTY_PREMISES_ZIP_CODE,
    INVALID_PREMISES_ZIP_CODE_255C,
    MAX_LENGTH_PREMISES_ZIP_CODE,
    INVALID_PREMISES_ZIP_CODE_255B,
    NUMERIC_PREMISES_ZIP_CODE_255A,
    LOWERCASE_PREMISES_ZIP_CODE_STEP2,

    //premises County Code
    EMPTY_PREMISES_COUNTY_CODE,
    MIN_LENGTH_PREMISES_COUNTY_CODE,
    ALPHANUMERIC_PREMISES_COUNTY_CODE,


    //SeparateBillingAddress
    NULL_SEPARATE_BILLING_ADDRESS,
    MIN_LENGTH_SEPARATE_BILLING_ADDRESS,


}
