package com.gng.api.steps.serviceTransfer.ServiceOrdersSteps.SaveUnenrollment;

public enum SaveUnenrollmentApiLabel {

    save_unenrollment,
    save_unenrollment_mandatory,

    // Request ID
    REQUEST_ID_EMPTY_NEGATIVE_TC97,
    REQUEST_ID_MAX_LENGTH_NEGATIVE_TC98,
    REQUEST_ID_DUPLICATE_NEGATIVE_TC99,

    // Login ID
    LOGIN_ID_EMPTY_NEGATIVE_TC100,
    LOGIN_ID_MAX_LENGTH_NEGATIVE_TC101,
    LOGIN_ID_INVALID_FORMAT_NEGATIVE_TC102,
    LOGIN_ID_NOT_EXISTS_NEGATIVE_TC103,

    // Transaction Type
    TRANSACTION_TYPE_EMPTY_NEGATIVE_TC104,
    TRANSACTION_TYPE_MAX_LENGTH_NEGATIVE_TC105,
    TRANSACTION_TYPE_INVALID_NEGATIVE_TC106,

    // Customer Code
    CUSTOMER_CODE_EMPTY_NEGATIVE_TC107,
    CUSTOMER_CODE_MAX_LENGTH_NEGATIVE_TC108,
    CUSTOMER_CODE_NON_INT_NEGATIVE_TC109,
    CUSTOMER_CODE_NOT_EXISTS_NEGATIVE_TC110,

    // Premises Code
    PREMISES_CODE_EMPTY_NEGATIVE_TC111,
    PREMISES_CODE_MAX_LENGTH_NEGATIVE_TC112,
    PREMISES_CODE_NOT_EXISTS_NEGATIVE_TC113,

    // Account Combo
    ACCOUNT_COMBINATION_INVALID_NEGATIVE_TC114,

    // AGLC Account
    AGLC_ACCOUNT_EMPTY_NEGATIVE_TC115,
    AGLC_ACCOUNT_MAX_LENGTH_NEGATIVE_TC116,

    // Forwarding Address
    FWD_ADDRESS_EMPTY_NEGATIVE_TC117,
    FWD_ADDRESS_MAX_LENGTH_NEGATIVE_TC118,
    FWD_ADDRESS_INVALID_VALUE_NEGATIVE_TC119,

    FWD_ADDRESS_TYPE_INVALID_NEGATIVE_TC120,
    FWD_ADDRESS_TYPE_EMPTY_NEGATIVE_TC121,
    FWD_ADDRESS_TYPE_INVALID_VALUE_NEGATIVE_TC122,

    FWD_ADD_STR_NUM_MAX_LENGTH_NEGATIVE_TC123,
    FWD_ADD_STR_PRE_DIR_MAX_LENGTH_NEGATIVE_TC124,
    FWD_ADD_STR_NAME_EMPTY_NEGATIVE_TC125,
    FWD_ADD_STR_NAME_MAX_LENGTH_NEGATIVE_TC126,
    FWD_ADD_STR_SFX_MAX_LENGTH_NEGATIVE_TC127,
    FWD_ADD_STR_POST_DIR_MAX_LENGTH_NEGATIVE_TC128,
    FWD_ADD_UNIT_TYPE_MAX_LENGTH_NEGATIVE_TC129,
    FWD_ADD_UNIT_NUM_MAX_LENGTH_NEGATIVE_TC130,
    FWD_ADD_RURAL_ROUTE_MAX_LENGTH_NEGATIVE_TC131,
    FWD_ADD_PO_BOX_MAX_LENGTH_NEGATIVE_TC132,
    FWD_ADD_LINE2_MAX_LENGTH_NEGATIVE_TC133,
    FWD_ADD_CITY_EMPTY_NEGATIVE_TC134,
    FWD_ADD_CITY_MAX_LENGTH_NEGATIVE_TC135,
    FWD_ADD_STATE_CODE_EMPTY_NEGATIVE_TC136,
    FWD_ADD_STATE_CODE_MAX_LENGTH_NEGATIVE_TC137,
    FWD_ADD_STATE_CODE_INVALID_NEGATIVE_TC138,
    FWD_ADD_ZIP_CODE_EMPTY_NEGATIVE_TC139,
    FWD_ADD_ZIP_CODE_MAX_LENGTH_NEGATIVE_TC140,
    FWD_ADD_ZIP_CODE_INVALID_NEGATIVE_TC141,
    FWD_ADD_ZIP_CODE_INVALID_FORMAT_NEGATIVE_TC142,

    // Turn Off Reason / Sub Reason
    TURN_OFF_REASON_EMPTY_NEGATIVE_TC143,
    TURN_OFF_REASON_MAX_LENGTH_NEGATIVE_TC144,
    TURN_OFF_REASON_INVALID_NEGATIVE_TC145,

    TURN_OFF_SUB_REASON_EMPTY_NEGATIVE_TC146,
    TURN_OFF_SUB_REASON_MAX_LENGTH_NEGATIVE_TC147,
    TURN_OFF_SUB_REASON_EMPTY_MOVING_NEGATIVE_TC148,
    TURN_OFF_SUB_REASON_MAX_LENGTH_MOVING_NEGATIVE_TC149,

    // Invalid Reason/SubReason for Service Transfer
    TURN_OFF_REASON_INVALID_FOR_SERVICE_TRANSFER_NEGATIVE_TC150,
    TURN_OFF_REASON_INVALID_FOR_SERVICE_TRANSFER_NEGATIVE_TC151,
    TURN_OFF_REASON_INVALID_FOR_SERVICE_TRANSFER_NEGATIVE_TC152,
    TURN_OFF_REASON_INVALID_FOR_SERVICE_TRANSFER_NEGATIVE_TC153,
    TURN_OFF_SUB_REASON_INVALID_FOR_SERVICE_TRANSFER_NEGATIVE_TC154,
    TURN_OFF_SUB_REASON_INVALID_FOR_SERVICE_TRANSFER_NEGATIVE_TC155,
    TURN_OFF_SUB_REASON_INVALID_FOR_SERVICE_TRANSFER_NEGATIVE_TC156,
    TURN_OFF_REASON_INVALID_FOR_SERVICE_TRANSFER_NEGATIVE_TC157,
    TURN_OFF_REASON_INVALID_FOR_SERVICE_TRANSFER_NEGATIVE_TC158,
    TURN_OFF_REASON_INVALID_FOR_SERVICE_TRANSFER_NEGATIVE_TC159,
    TURN_OFF_REASON_INVALID_FOR_SERVICE_TRANSFER_NEGATIVE_TC160,
    TURN_OFF_REASON_INVALID_FOR_SERVICE_TRANSFER_NEGATIVE_TC161,
    TURN_OFF_REASON_INVALID_FOR_SERVICE_TRANSFER_NEGATIVE_TC162,
    TURN_OFF_REASON_INVALID_FOR_SERVICE_TRANSFER_NEGATIVE_TC163,
    TURN_OFF_REASON_INVALID_FOR_SERVICE_TRANSFER_NEGATIVE_TC164,
    TURN_OFF_REASON_INVALID_FOR_SERVICE_TRANSFER_NEGATIVE_TC165,
    TURN_OFF_REASON_INVALID_FOR_SERVICE_TRANSFER_NEGATIVE_TC166,
    TURN_OFF_REASON_INVALID_FOR_SERVICE_TRANSFER_NEGATIVE_TC167,
    TURN_OFF_REASON_INVALID_FOR_SERVICE_TRANSFER_NEGATIVE_TC168,
    TURN_OFF_REASON_INVALID_FOR_SERVICE_TRANSFER_NEGATIVE_TC169,
    TURN_OFF_REASON_INVALID_FOR_SERVICE_TRANSFER_NEGATIVE_TC170,
    TURN_OFF_REASON_INVALID_FOR_SERVICE_TRANSFER_NEGATIVE_TC171,
    TURN_OFF_REASON_INVALID_FOR_SERVICE_TRANSFER_NEGATIVE_TC172,
    TURN_OFF_REASON_INVALID_FOR_SERVICE_TRANSFER_NEGATIVE_TC173,

    TURN_OFF_SUB_REASON_MISSING_FOR_SERVICE_TRANSFER_NEGATIVE_TC174A,
    TURN_OFF_SUB_REASON_MISSING_FOR_SERVICE_TRANSFER_NEGATIVE_TC174B,

    EMAIL_ADDRESS_INVALID_LENGTH_NEGATIVE_TC175A,
    EMAIL_ADDRESS_INVALID_FORMAT_NEGATIVE_TC175B,

    // requestedTurnOffDate
    REQUESTED_TURNOFF_DATE_MISSING_NEGATIVE_TC176,
    REQUESTED_TURNOFF_DATE_INVALID_NEGATIVE_TC177,

    // aglcServiceOrderNumber
    AGLC_SERVICE_ORDER_NUMBER_MISSING_NEGATIVE_TC178,
    AGLC_SERVICE_ORDER_NUMBER_INVALID_LENGTH_MAX_NEGATIVE_TC179,
    AGLC_SERVICE_ORDER_NUMBER_INVALID_LENGTH_MIN_NEGATIVE_TC180,

    // etcExists
    ETC_EXISTS_MISSING_NEGATIVE_TC181,
    ETC_MISSING_NEGATIVE_TC182,

    // marketerReferenceData
    MRD_INVALID_VALUE_NEGATIVE_TC183,
    MRD_LENGTH_MAX_NEGATIVE_TC184,
    MRD_LENGTH_MIN_NEGATIVE_TC185,
    MRD_DUPLICATE_NEGATIVE_TC186,
    MRD_NOT_NUMERIC_NEGATIVE_TC187,


    //Address types
    ADDRESS_TYPE_STREET,
    ADDRESS_TYPE_RURAL,
    ADDRESS_TYPE_POBOX,
    ADDRESS_TYPE_NOT_PRESENT,

    ACN_RS_REMAINS_ON_TIER_1_TC_251,
    ACN_RS_REMAINS_ON_TIER_1_NACN_TC_252,
    ACN_RS_TC_253,
    NACN_RS_TC_254,
    ACN_RS_TC_255,
    NACN_RS_TC_256,
    NACN_SR_TC_258,
    ACN_RS_TC_259,
    NACN_RS_TC_260,
    NACN_SR_TC_262,
    ACN_RS_TC_263,
    NACN_RS_TC_264,
    ACN_RS_TC_265,
    NACN_RS_TC_266,
    NACN_RS_TC_267,
    ACN_RS_TC_268,
    ACN_RS_TC_269,
    NACN_RS_TC_270,
    ACN_RS_TC_271,
    ACN_RS_TC_273,
    ACN_RS_TC_274,
    ACN_RS_TC_275,
    NACN_RS_TC_276,
    NACN_RS_TC_277,
    ACN_RS_TC_278,
    NACN_RS_TC_279,
    NACN_RS_TC_280,
    ACN_CM_TC_281,
    NACN_CM_TC_282,
    NACN_CM_TC_283,
    ACN_CM_TC_284,
    NACN_RS_TC_285,
    NACN_RS_TC_286,
    NACN_CM_TC_287,
    NACN_CM_TC_288,
    NACN_RS_TC_289,
    NACN_RS_TC_290,
    NACN_RS_TC_291,
    NACN_RS_TC_292,
    NACN_RS_TC_293,
    NACN_RS_TC_294,
    NACN_RS_TC_295,
    NACN_RS_TC_296,
    NACN_RS_TC_297,
    ACN_RS_TC_298,
    NACN_RS_TC_300,
    NACN_CM_TC_301


}
