package com.gng.api.steps.marketerSwitch.ServiceOrdersSteps.GetEligiblePlansAndOffers;

public enum GetEligiblePlansAndOffersApiLabel {

    get_eligible_plans_and_offers,
    get_eligible_plans_and_offers_mandatory,


    GE_MRK_SW_VAL_MISSING_TRANSACTION_TYPE_TC04,
    GE_MRK_SW_VAL_TRANSACTION_TYPE_MAX_LENGTH_TC05,
    GE_MRK_SW_VAL_INVALID_TRANSACTION_TYPE_TC06,
    GE_MRK_SW_VAL_MISSING_AGLC_ACCOUNT_NUMBER_TC07,
    GE_MRK_SW_VAL_MISSING_AGLC_SERVICE_LOCATION_ID_TC08,
    GE_MRK_SW_RS_NEW_CC_YES_INVALID_SSN_FRAUD_ALERT_11114_TC09,
    GE_MRK_SW_RS_NEW_CC_YES_NO_RECORD_CONFIRM_FALSE_11112_TC10,
    GE_MRK_SW_RS_NEW_CC_YES_NO_RECORD_CONTINUE_UC50_TC11,
    GE_MRK_SW_RS_NEW_CC_YES_UC50_ALT_PATH_TC12,
    GE_MRK_SW_RS_NEW_CC_YES_UC52_TC13,
    GE_MRK_SW_RS_NEW_CC_YES_UC63_TC14,
    GE_MRK_SW_RS_NEW_CC_YES_UC47_TC15,
    GE_MRK_SW_RS_NEW_CC_NO_DENIED_BY_CUSTOMER_TC16,
    GE_MRK_SW_RS_NEW_CC_YES_TIER1_VALUE100_CREDIT700_999_SSP_FALSE_TC17,
    GE_MRK_SW_RS_NEW_CC_YES_TIER2_VALUE101_CREDIT600_699_SSP_FALSE_TC18,
    GE_MRK_SW_RS_NEW_CC_YES_TIER_UC45_TC19,
    GE_MRK_SW_RS_NEW_CC_COMM_CREDIT_OPTION_9998_TC20,
    GE_MRK_SW_RS_NEW_CC_YES_ACN_LANDLORD_BYPASS_CREDIT_TC21,
    GE_MRK_SW_RS_NEW_CC_YES_UC65_TC22,
    GE_MRK_SW_RS_NEW_CC_YES_MULTI_PREMISES_MATCH_UC71_TC23,
    GE_MRK_SW_RS_CRDS_CC_YES_DEPOSIT_BILLED_VALUE110_TC24,
    GE_MRK_SW_CM_NEW_CC_YES_UC53_TC25,
    GE_MRK_SW_CM_NEW_CC_YES_BIN_NULL_NO_MATCH_CONTINUE_TC26,
    GE_MRK_SW_CM_NEW_CC_YES_BIN_NOT_NULL_SELECT_SIMILAR_BUSINESS_TC27,
    GE_MRK_SW_CM_NEW_CC_YES_TIER_EXCELLENT_VALUE200_CREDIT50_100_TC28,
    GE_MRK_SW_CM_NEW_CC_YES_COMM_DEPOSIT_PROSPECT_UC72_TC29,
    GE_MRK_SW_CM_CRDS_CC_YES_COMM_DEPOSIT_PROSPECT_UC73_TC30,
    GE_MRK_SW_CM_CRDS_CC_YES_COMM_DEPOSIT_PROSPECT_UC72_TC31,
    GE_MRK_SW_CM_CRDS_CC_YES_PROMO_DEPOSIT_REQUIRED_VALUE210_CREDIT0_49_TC32,
    GE_MRK_SW_CM_CRDS_CC_YES_DEPOSIT_REQUIRED_BUSINESS_NAME_POPULATED_UC42_TC33

}
