package com.gng.api.steps.csi.GetBillHistory;

public enum GetBillHistoryLabel {

    get_bill_history,
    get_bill_history_mandatory,

    TC_60__Negative__Missing_Request_ID,
    TC_61__Negative__Invalid_Request_ID_Length,
    TC_62__Negative__Duplicate_Request_ID,
    TC_63__Negative__Missing_customerCode,
    TC_64__Negative__Invalid_customerCode_Length,
    TC_65__Negative__Invalid_customerCode_Format,
    TC_66__Negative__Missing_premisesCode,
    TC_67__Negative__Invalid_premisesCode_Length,
    TC_68__Negative__Invalid_premisesCode_Format,
    TC_69__Negative__Invalid_Account_Number,
    TC_70__Negative__Missing_Number_of_Months,
    TC_71__Negative__Invalid_Number_of_Months_Format_NotANumber,
    TC_72__Negative__Invalid_Number_of_Months_Zero,
    TC_73__Negative__Invalid_Number_of_Months_Negative,
    TC_74__Negative__Invalid_Number_of_Months_Length,

    TC_75__Positive__Usage_History_BillDate_Format,
    TC_76__Positive__Usage_History_UsageFromDate_Format,
    TC_77__Positive__Usage_History_UsageToDate_Format,
    TC_78__Positive__Usage_History_DaysOfService_Format,
    TC_79__Positive__Usage_History_HeatingDegreeDays_Format,
    TC_80__Positive__Usage_History_TotalBilledConsumption_Format,
    TC_81__Positive__Usage_History_BalanceBroughtForward_Format,
    TC_82__Positive__Usage_History_GasServiceCharges_Format,
    TC_83__Positive__Usage_History_OtherCharges_Format,
    TC_84__Positive__Usage_History_PromotionalDiscounts_Format,
    TC_85__Positive__Usage_History_Taxes_Format,
    TC_86__Positive__Usage_History_BudgetBillingAmount_Format,
    TC_87__Positive__Usage_History_NotBudgetBillingAccount,
    TC_88__Positive__Usage_History_TotalBillAmount_Format,
    TC_89__Positive__Usage_History_BillHistoryTransactionNumber_Format,
    TC_90__Positive__No_Usage_History_Active,
    TC_91__Positive__No_Usage_History_Final,
    TC_92__Positive__No_Usage_History_Inactive,
    TC_93__Positive__Valid_NumberOfMonths_BillHistory_Too_Old,
    TC_94__Positive__Usage_History_Less_Than_Requested_Months,
    TC_95__Positive__Usage_History_Equals_Requested_Months,
    TC_96__Positive__Usage_History_Greater_Than_Requested_Months
}
