package com.gng.api.steps.csi.GetBillHistory;

public enum GetBillHistoryLabel {

    get_bill_history,
    get_bill_history_mandatory,

    TC_11__Negative__Missing_Request_ID,
    TC_12__Negative__Invalid_Request_ID_Length,
    TC_13__Negative__Duplicate_Request_ID,
    TC_14__Negative__Missing_customerCode,
    TC_15__Negative__Invalid_customerCode_Length,
    TC_16__Negative__Invalid_customerCode_Format,
    TC_17__Negative__Missing_premisesCode,
    TC_18__Negative__Invalid_premisesCode_Length,
    TC_19__Negative__Invalid_premisesCode_Format,
    TC_20__Negative__Invalid_Account_Number,
    TC_21__Negative__Missing_Number_of_Months,
    TC_22__Negative__Invalid_Number_of_Months_Format_NotANumber,
    TC_23__Negative__Invalid_Number_of_Months_Zero,
    TC_24__Negative__Invalid_Number_of_Months_Negative,
    TC_25__Negative__Invalid_Number_of_Months_Length,
    TC_26__Negative__New_Account_Not_Allowed,

    TC_27__Positive__Usage_History_BillDate_Format,
    TC_28__Positive__Usage_History_UsageFromDate_Format,
    TC_29__Positive__Usage_History_UsageToDate_Format,
    TC_30__Positive__Usage_History_DaysOfService_Format,
    TC_31__Positive__Usage_History_HeatingDegreeDays_Format,
    TC_32__Positive__Usage_History_TotalBilledConsumption_Format,
    TC_33__Positive__Usage_History_BalanceBroughtForward_Format,
    TC_34__Positive__Usage_History_GasServiceCharges_Format,
    TC_35__Positive__Usage_History_OtherCharges_Format,
    TC_36__Positive__Usage_History_PromotionalDiscounts_Format,
    TC_37__Positive__Usage_History_Taxes_Format,
    TC_38__Positive__Usage_History_BudgetBillingAmount_Format,
    TC_39__Positive__Usage_History_NotBudgetBillingAccount,
    TC_40__Positive__Usage_History_TotalBillAmount_Format,
    TC_41__Positive__Usage_History_BillHistoryTransactionNumber_Format,
    TC_42__Positive__No_Usage_History_Active,
    TC_43__Positive__No_Usage_History_Final,
    TC_44__Positive__No_Usage_History_Inactive,
    TC_45__Positive__Valid_NumberOfMonths_BillHistory_Too_Old,
    TC_46__Positive__Usage_History_Less_Than_Requested_Months,
    TC_47__Positive__Usage_History_Equals_Requested_Months,
    TC_48__Positive__Usage_History_Greater_Than_Requested_Months
}
