package com.gng.api.steps.AccountsApiSteps.SearchAccounts;

public enum SearchAccountsApiLabel {

    search_accounts,
    search_accounts_mandatory,

    //requestID
    NULL_REQUEST_ID_TC42,
    DUPLICATE_REQUEST_ID_TC43,
    LONG_REQUEST_ID_TC44,

    //loginID
    NULL_LOGIN_ID_TC45,
    ALPHANUMERIC_LOGIN_ID_TC47,
    MAX_LENGTH_LOGIN_ID_TC46,
    INVALID_LOGIN_ID_NOT_PRESENT_USER_TABLE_TC48,

    MAX_LENGTH_CUSTOMER_CODE_TC49,
    MAX_LENGTH_PREMISES_CODE_TC50,

    //transactionType
    MISSING_TRANSACTION_TYPE_TC51,
    INVALID_TRANSACTION_TYPE_TC52,

    MAX_LENGTH_BUSINESS_NAME_TC53,
    MAX_LENGTH_LAST_NAME_TC54,
    MAX_LENGTH_FIRST_NAME_TC55,
    NOT_ENCRYPTED_SOCIAL_SECURITY_NUMBER_TC56,
    ENCRYPTED_SOCIAL_SECURITY_NUMBER_TC57,
    NOT_ENCRYPTED_FEDERAL_TAX_ID_TC58,
    ENCRYPTED_FEDERAL_TAX_ID_TC59,
    MAX_LENGTH_PHONE_NUMBER_TC60,
    MAX_LENGTH_AGLC_ACCOUNT_NUMBER_TC61,
    MAX_LENGTH_PREMISES_STREET_NUMBER_TC62,
    MAX_LENGTH_PREMISES_STREET_PRE_DIRECTION_TC63,
    MAX_LENGTH_PREMISES_STREET_NAME_TC64,
    MAX_LENGTH_PREMISES_STREET_SUFFIX_TC65,
    MAX_LENGTH_PREMISES_STREET_POST_DIRECTION_TC66,
    MAX_LENGTH_PREMISES_UNIT_TYPE_TC67,
    MAX_LENGTH_PREMISES_UNIT_NUMBER_TC68,
    MAX_LENGTH_PREMISES_CITY_TC69,
    MAX_LENGTH_PREMISES_STATE_CODE_TC70,
    MAX_LENGTH_PREMISES_ZIP_CODE_TC71,
    CUSTOMER_CODE_PROVIDED_PREMISES_CODE_MISSING_TC73,
    CUSTOMER_CODE_MISSING_PREMISES_CODE_PROVIDED_TC74,
    CUSTOMER_FIRST_NAME_PROVIDED_CUSTOMER_LAST_NAME_MISSING_TC75,
    CUSTOMER_LAST_NAME_PROVIDED_PREMISES_ZIP_MISSING_TC76,
    SSN_PROVIDED_FEDERAL_TAX_ID_PROVIDE_TC77,

    //streetNameMissing
    PREMISES_STREET_NUMBER_PROVIDED_PREMISES_STREET_NAME_MISSING_TC78,
    PREMISES_STREET_PRE_DIRECTION_PROVIDED_PREMISES_STREET_NAME_MISSING_TC79,
    PREMISES_STREET_SUFFIX_PROVIDED_PREMISES_STREET_NAME_MISSING_TC80,
    PREMISES_STREET_POST_DIRECTION_PROVIDED_PREMISES_STREET_NAME_MISSING_TC81,
    PREMISES_STREET_NUMBER_PREMISES_STREET_PRE_DIRECTION_PROVIDED_PREMISES_STREET_NAME_MISSING_TC82,
    PREMISES_STREET_NUMBER_PREMISES_STREET_SUFFIX_PROVIDED_PREMISES_STREET_NAME_MISSING_TC83,
    PREMISES_STREET_NUMBER_PREMISES_STREET_POST_DIRECTION_PROVIDED_PREMISES_STREET_NAME_MISSING_TC84,
    PREMISES_STREET_PRE_DIRECTION_PREMISES_STREET_SUFFIX_PROVIDED_PREMISES_STREET_NAME_MISSING_TC85,
    PREMISES_STREET_PRE_DIRECTION_PREMISES_STREET_POST_DIRECTION_PROVIDED_PREMISES_STREET_NAME_MISSING_TC86,
    PREMISES_STREET_SUFFIX_PREMISES_STREET_POST_DIRECTION_PROVIDED_PREMISES_STREET_NAME_MISSING_TC87,
    PREMISES_STREET_NUMBER_SUFFIX_PRE_DIRECTION_PROVIDED_PREMISES_STREET_NAME_MISSING_TC88,
    PREMISES_STREET_NUMBER_SUFFIX_POST_DIRECTION_PROVIDED_PREMISES_STREET_NAME_MISSING_TC89,
    PREMISES_PRE_DIRECTION_SUFFIX_POST_DIRECTION_PROVIDED_PREMISES_STREET_NAME_MISSING_TC90,
    PREMISES_STREET_NUMBER_PRE_DIRECTION_POST_DIRECTION_PROVIDED_PREMISES_STREET_NAME_MISSING_TC91,
    PREMISES_STREET_NUMBER_SUFFIX_PRE_DIRECTION_POST_DIRECTION_PROVIDED_PREMISES_STREET_NAME_MISSING_TC92,

    //missingAddressFields

    PREMISES_STREET_NAME_PROVIDED_CITY_ZIP_STATE_CODE_MISSING_TC93,
    PREMISES_CITY_PROVIDED_STREET_NAME_ZIP_STATE_CODE_MISSING_TC94,
    PREMISES_STATE_CODE_PROVIDED_STREET_NAME_ZIP_CITY_MISSING_TC95,
    PREMISES_ZIP_CODE_PROVIDED_STREET_NAME_ZIP_STATE_MISSING_TC96,
    PREMISES_STREET_NAME_CITY_PROVIDED_ZIP_STATE_MISSING_TC97,
    PREMISES_STREET_NAME_STATE_PROVIDED_ZIP_CITY_MISSING_TC98,
    PREMISES_STREET_NAME_ZIP_PROVIDED_STATE_CITY_MISSING_TC99,
    PREMISES_STATE_CITY_PROVIDED_STREET_NAME_ZIP_MISSING_TC100,

    PREMISES_STATE_CITY_ZIP_PROVIDED_STREET_NAME_STATE_MISSING_TC101,
    PREMISES_STATE_ZIP_PROVIDED_STREET_NAME_CITY_MISSING_TC102,
    PREMISES_STATE_STREET_NAME_CITY_PROVIDED_ZIP_MISSING_TC103,
    PREMISES_STATE_STREET_NAME_PROVIDED_CITY_MISSING_TC104,
    PREMISES_ZIP_STREET_NAME_CITY_PROVIDED_STATE_MISSING_TC105,
    PREMISES_ZIP_STATE_CITY_PROVIDED_STREET_NAME_MISSING_TC106,


    //POSITIVE TEST CASES

    CUSTMER_CODE_NOT_PRESENT_IN_DATATABLE_TC107,
    ACCOUNT_NUMBER_WITHOUT_SSN_FROM_USER_TABLE_TC109,
    SSP_PARTICIPATED_CODE_WITH_CUSTOMER_CODE_TC121e



}
