package com.gng.api.steps.serviceTransfer.Common.GetReasonsForLeaving;

public enum GetReasonsForLeavingApiLabel {

    get_reasons_for_leaving,
    get_reasons_for_leaving_mandatory,

    // Negative
    DUPLICATE_REQUEST_ID_NEGATIVE_TC76,
    MISSING_REQUEST_ID_NEGATIVE_TC77,
    INVALID_REQUEST_ID_LENGTH_NEGATIVE_TC78,
    MISSING_LOGIN_ID_NEGATIVE_TC79,
    INVALID_LOGIN_ID_TOO_LONG_NEGATIVE_TC80,
    INVALID_LOGIN_ID_NOT_ALPHANUMERIC_NEGATIVE_TC81,
    INVALID_LOGIN_ID_NOT_FOUND_NEGATIVE_TC82,
    MISSING_ETC_EXISTS_NEGATIVE_TC83,
    MISSING_TRANSACTION_TYPE_NEGATIVE_TC84,
    INVALID_TRANSACTION_TYPE_VALUE_NEGATIVE_TC85,
    INVALID_TRANSACTION_TYPE_LENGTH_NEGATIVE_TC86,

    // Positive
    ETC_EXISTS_TRUE_RETURNS_MOVING_SERVICE_TRANSFER_POSITIVE_TC87,
    ETC_EXISTS_FALSE_RETURNS_NO_RECORDS_POSITIVE_TC88
}
