package com.gng.api.steps.turnOn.UsersApiSteps.ResetPassword;

public enum ResetPasswordApiLabel {

    reset_password,
    reset_password_mandatory,

    //requestID
    WITHOUT_REQUEST_ID_TC21,
    NULL_REQUEST_ID_TC21A,
    DUPLICATE_REQUEST_ID_TC22,
    LONG_REQUEST_ID_TC23,


    //loginId
    WITHOUT_LOGIN_ID_AND_OLD_PASSWORD_TC24,
    NULL_LOGIN_ID_AND_OLD_PASSWORD_TC24A,
    WITHOUT_LOGIN_ID_TC25,
    NULL_LOGIN_ID_TC25A,
    MAX_LENGTH_LOGIN_ID_TC26,
    SPECIAL_CHAR_LOGIN_ID_TC27,
    INVALID_LOGIN_ID_NOT_IN_USER_TABLE_TC28,

    //oldPassword
    WITHOUT_OLD_PASSWORD_TC29,
    NULL_OLD_PASSWORD_TC29A,
    UNENCRYPTED_OLD_PASSWORD_TC30,
    ENCRYPTED_OLD_PASSWORD_MORE_THAN_10_CHAR_TC31,
    ENCRYPTED_OLD_PASSWORD_LESS_THAN_7_CHAR_TC31A,
    ENCRYPTED_OLD_PASSWORD_WITH_8_CHAR_WITH_SPECIAL_CHAR_TC31B,
    INCORRECT_PASSWORD_UNBLOCK_USER_TC36,
    INCORRECT_PASSWORD_BLOCK_USER_TC37,
    INVALID_PASSWORD_TEST_CONDITION,




    //newPassword
    WITHOUT_NEW_PASSWORD_TC32,
    NULL_NEW_PASSWORD_TC32A,
    UNENCRYPTED_NEW_PASSWORD_TC33,
    ENCRYPTED_NEW_PASSWORD_MORE_THAN_10_CHAR_TC34,
    ENCRYPTED_NEW_PASSWORD_LESS_THAN_7_CHAR_TC34A,
    ENCRYPTED_OLD_PASSWORD_WITH_8_CHAR_WITH_SPECIAL_CHAR_TC34B,
    OLD_PASSWORD_NEW_PASSWORD_SAME_TC35,
    NOT_EXPIRED_PASSWORD_TC_39,
    EXPIRED_PASSWORD_TC_40



}
