package com.gng.api.steps.csi.GetPaperlessEnrollmentEligibility;

public enum GetPaperlessEnrollmentEligibilityLabel {

    get_paperless_enrollment_eligibility,

    TC_154__Negative__Missing_Request_ID_,
    TC_155__Negative__Invalid_Request_ID_Length_,
    TC_156__Negative__Duplicate_Request_ID_,
    TC_157__Negative__Missing_customerCode_,
    TC_158__Negative__Invalid_customerCode_Length_,
    TC_159__Negative__Invalid_customerCode_Format_,
    TC_160__Negative__Missing_premisesCode_,
    TC_161__Negative__Invalid_premisesCode_Length_,
    TC_162__Negative__Invalid_premisesCode_Format_,
    TC_163__Negative__Invalid_Account_Number__Invalid_Account_,

    TC_164__Positive__Corr_Delivery_Option_Format_,
    TC_165__Positive__Bill_Delivery_Option_Format_,
    TC_166__Positive__Corr_Eligible_Format_,

    TC_167__Positive__Bill_Eligible_Format_,
    TC_168__Positive__Corr_Reason_Code_Format_,
    TC_169__Positive__Bill_Reason_Code_Format_,
    TC_170__Positive__Corr_Reason_Desc_Format_,
    TC_171__Positive__Bill_Reason_Desc_Format_,
    TC_172__Positive__Correspondence_NULL_Defaults_to_P_,
    TC_173__Positive__Correspondence_P_Mapping_,
    TC_174__Positive__Correspondence_E_Mapping_,
    TC_175__Positive__Bill_NULL_Defaults_to_P_,
    TC_176__Positive__Bill_P_Mapping_,
    TC_177__Positive__Bill_E_Mapping_,
    TC_178__Positive__Bill_F_Mapping_,

    TC_179__Positive__Corr_Ineligible_No_Email_,
    TC_180__Positive__Bill_Ineligible_No_Email_,
    TC_181__Positive__Corr_Reason_Code_1_,
    TC_182__Positive__Bill_Reason_Code_1_,
    TC_183__Positive__Corr_Eligible_,
    TC_184__Positive__Corr_Ineligible_Enrolled_,
    TC_185__Positive__Bill_Eligible_,
    TC_186__Positive__Bill_Ineligible_Enrolled_,
    TC_187__Positive__Bill_Ineligible_Fiserv_,
    TC_188__Positive__Corr_Reason_Code_2_,
    TC_189__Positive__Bill_Reason_Code_2_,
    TC_190__Positive__Bill_Reason_Code_4_,
    TC_191__Positive__Corr_Reason_Description_,
    TC_192__Positive__Bill_Reason_Description_,
    TC_193__Positive__Corr_Reason_Description_NULL_,
    TC_194__Positive__Bill_Reason_Description_NULL_,
    TC_195__Positive__Corr_Override_I_,
    TC_196__Positive__Corr_Override_Ineligible_,
    TC_197__Positive__Corr_Override_Reason_3_,
    TC_198__Positive__Bill_Override_I_,
    TC_199__Positive__Bill_Override_Ineligible_,
    TC_200__Positive__Bill_Override_Reason_3_,
    TC_201__Positive__Corr_Override_Precedence_,
    TC_202__Positive__Bill_Override_Precedence_,
    TC_203__Positive__PPER_Overrides_Email_Rule_,
    TC_204__Positive__New_Unconfirmed_Bill_,
    TC_205__Positive__New_Confirmed_Bill_
}
