package com.gng.api.steps.meterSet.ServiceOrdersSteps.SaveEnrollment;

public enum SaveEnrollmentApiLabel {
    save_enrollment,

    // SaveEnrollment - Meter Set (SETM) Negative Scenarios
    MS_SE_MISSING_TRANSACTION_TYPE_TC_035,
    MS_SE_TRANSACTION_TYPE_MAX_LENGTH_TC_036,
    MS_SE_TRANSACTION_TYPE_INVALID_VALUE_TC_037,

    MS_SE_SSP_RESULT_SHOULD_BE_NULL_TC_038,
    MS_SE_AGLC_ACCOUNT_NUMBER_SHOULD_BE_NULL_TC_039,
    MS_SE_AGLC_SERVICE_ORDER_NUMBER_SHOULD_BE_NULL_TC_040,
    MS_SE_SSP_PARTICIPANT_CODE_SHOULD_BE_NULL_TC_041,
    MS_SE_CURRENT_MARKETER_CODE_SHOULD_BE_NULL_TC_042,

    MS_SE_MISSING_REQUESTED_TURN_ON_DATE_TC_043,
    MS_SE_REQUESTED_TURN_ON_DATE_INVALID_FORMAT_TC_044,

    // Budget Billing rules
    MS_SE_BUDGET_BILLING_PRP_NULL_AMOUNT_NOT_ALLOWED_TC_044_1,
    MS_SE_BUDGET_BILLING_PRP_AMOUNT_PROVIDED_NOT_ALLOWED_TC_044_2,
    MS_SE_BUDGET_BILLING_NON_PRP_MISSING_AMOUNT_TC_044_3,
    MS_SE_BUDGET_BILLING_NON_PRP_AMOUNT_TOO_LONG_TC_044_4,
    MS_SE_BUDGET_BILLING_NON_PRP_DECIMAL_AMOUNT_INVALID_TC_044_5,
    MS_SE_BUDGET_BILLING_PLAN_CODE_MISSING_TC_044_6,



    //positive
    MS_SE_RS_B_ENROLLMENT_STATUS_CE_TC_045,
    MS_SE_CM_R_ENROLLMENT_STATUS_DP_TC_046,
    MS_SE_RS_R_ENROLLMENT_STATUS_PC_REQUOTE_TC_047,
    MS_SE_RS_PRP_ENROLLMENT_STATUS_DB_TC_048,
    MS_SE_CM_R_ENROLLMENT_STATUS_SI_TC_049,
    MS_SE_RS_R_ENROLLMENT_STATUS_DR_TC_050,
    MS_SE_RS_NA_ENROLLMENT_STATUS_RP_PRP_TC_050A,
    MS_SE_RS_PRP_ENROLLMENT_STATUS_PR_TC_051,
    // TC_052 is intentionally omitted (duplicate per FTD)
    MS_SE_CM_R_ENROLLMENT_STATUS_RD_PROMO_TC_053,
    MS_SE_RS_PRP_ENROLLMENT_STATUS_CP_TC_054,
    MS_SE_RS_B_ENROLLMENT_STATUS_BD_BUDGET_TC_055,
    MS_SE_CM_R_CE_WITH_NOTES_TC_056,

    //External
    MS_GE_RS_ACN_LAND_BYPASS_CREDIT_TC_022,
    MS_GE_RS_INCL_TIER_5_TC_023,
    MS_RS_MULTIPLE_PREM_TC_024,
    MS_RS_CRDS_ENROLLMENT_CREDIT_CHECK_TC_025,
    MS_CM_CRDS_EN_CREDIT_CHECK_YES_COMM_DEP_PROSP_TC_033,
    MS_CM_CRDS_EN_CREDIT_CHECK_YES_BUSINESS_NAME_TC_034,
    GP_MS_PREPAY_ONLY_PRP_TC60


}
