package com.gng.api.steps.serviceTransfer.ServiceOrdersSteps.SaveEnrollment;

public enum SaveEnrollmentApiLabel {
    save_enrollment,

    ST_SE_MISSING_TRANSACTION_TYPE_TC229,
    ST_SE_INVALID_TRANSACTION_TYPE_LENGTH_TC230,
    ST_SE_INVALID_TRANSACTION_TYPE_VALUE_TC231,
    ST_SE_MISSING_ENROLLMENT_STATUS_TC232,
    ST_SE_INVALID_ENROLLMENT_STATUS_LENGTH_TC233,
    ST_SE_INVALID_ENROLLMENT_STATUS_VALUE_TC234,
    ST_SE_INVALID_ES_PAYMENT_CONFIRMATION_REQUIRED_TC235,
    ST_SE_INVALID_PAYMENT_CONFIRMATION_TC236,
    ST_SE_INVALID_SSP_PARTICIPANT_CODE_VALUE_TC237,
    ST_SE_SSP_PARTICIPANT_CODE_NOT_REQUIRED_TC238,
    ST_SE_MISSING_MARKETER_REFERENCE_CE_TRAN_TC239,
    ST_SE_DUPLICATE_MARKETER_REFERENCE_DATA_TC240,
    ST_SE_MARKETER_REFERENCE_DATA_INVALID_TYPE_TC242,
    ST_SE_MARKETER_REFERENCE_DATA_TOO_LONG_TC243,
    ST_SE_MARKETER_REFERENCE_DATA_TOO_SHORT_TC244,
    ST_SE_CURRENT_MARKETER_CODE_PROVIDED_TC245,
    ST_SE_REQUESTED_TURN_ON_DATE_PROVIDED_TC246,
    ST_SE_SERVICE_TRANSFER_REWARD_BOOLEAN_ONLY_TC247,
    ST_SE_CURRENT_PRICE_PLAN_FIXED_BOOLEAN_ONLY_TC248,
    ST_SE_CURRENT_PRICE_PLAN_CEILING_BOOLEAN_ONLY_TC249,
    ST_SE_CURRENT_PRICE_PLAN_APPLICABLE_FIXED_OR_CEILING_ONLY_TC250,

    //external
    ST_GE_ENROLLMENT_STATE_INVALID_FOR_TRAN_NEG_TC198,
    ACN_RS_TC_253,
    NACN_RS_TC_254,
    ACN_RS_TC_255,
    NACN_RS_TC_256,
    NACN_SR_TC_258
}

