package com.gng.api.steps.poc.CreateAccountNote;


public enum CreateAccountNoteApiLabel {

    create_account_note,
    create_account_note_mandatory,

    // Request ID
    REQUEST_ID_MISSING_NEGATIVE_TC65,
    REQUEST_ID_DUPLICATE_NEGATIVE_TC66,

    // Customer Code
    CUSTOMER_CODE_NULL_NEGATIVE_TC67,
    CUSTOMER_CODE_LENGTH_GT9_NEGATIVE_TC69,

    // Premises Code
    PREMISES_CODE_NULL_NEGATIVE_TC68,
    PREMISES_CODE_LENGTH_GT7_NEGATIVE_TC70,

    // Account Combination
    ACCOUNT_COMBINATION_INVALID_NEGATIVE_TC71,

    // Note Type / Text / Origin
    NOTE_TYPE_CODE_NULL_NEGATIVE_TC72,
    NOTE_TEXT_NULL_NEGATIVE_TC73,
    ORIGIN_NULL_NEGATIVE_TC74,

    // Dates
    EXPIRATION_DATE_INVALID_FORMAT_NEGATIVE_TC75,
    SUSPENSE_DATE_INVALID_FORMAT_NEGATIVE_TC76,

    // Service Number
    SERVICE_NUMBER_NOT_FOUND_FOR_PREMISES_NEGATIVE_TC77,
    SERVICE_NUMBER_INVALID_FORMAT_NEGATIVE_TC78,

    // Note Type validation
    NOTE_TYPE_INVALID_NEGATIVE_TC79,

    // Positive paths
    CREATE_NOTE_ACCT_POSITIVE_TC80,
    CREATE_NOTE_PMT_RPT_POSITIVE_TC81,
    CREATE_NOTE_IVR_NPA_POSITIVE_TC82,
    CREATE_NOTE_IVR_NPA_ALT_POSITIVE_TC83,
}
