package com.gng.api.steps.csi.AuthenticateCustomer;

public enum AuthenticateCustomerLabel {

    authenticate_customer,
    authenticate_customer_mandatory,

    TC_129__Negative__Missing_Request_ID,
    TC_130__Negative__Invalid_Request_ID__Length,
    TC_131__Negative__Duplicate_Request_ID,
    TC_132__Negative__Invalid_customerCode_Length,
    TC_133__Negative__Invalid_customerCode_Format,
    TC_134__Negative__Invalid_premisesCode_Length,
    TC_135__Negative__Invalid_premisesCode_Format,
    TC_136__Negative__Invalid_Last_or_Business_Name_Length,
    TC_137__Negative__Invalid_First_Name_Length,
    TC_138__Negative__Invalid_Last_Four_SSN_Length___Too_Long____,
    TC_139__Negative__Invalid_Last_Four_SSN_Length___Too_Short____,
    TC_140__Negative__Invalid_Federal_Tax_ID_Length___Too_Long____,
    TC_141__Negative__Invalid_Federal_Tax_ID_Length___Too_Short____,
    TC_142__Negative__Invalid_Email_Address_Format,
    TC_143__Negative__Invalid_Phone_Number_Length___Too_Long____,
    TC_144__Negative__Invalid_Phone_Number_Length___Too_Short____,
    TC_145__Negative__Invalid_Username_Format,
    TC_146__Negative__Inactive_Username,
    TC_147__Negative__Invalid_Password_Format_Length___Too_Short____,
    TC_148__Negative__Invalid_Password_Format_Length___Too_Long____,
    TC_149__Negative__Insufficient_Search_Criteria,
    TC_150__Negative__Last_4_SSN_____Password,
    TC_151__Negative__Last_4_SSN_____Username,
    TC_152__Negative__Last_4_SSN_____Customer_Code_____Premises_Code,
    TC_153__Negative__Last_4_SSN_____Federal_Tax_ID_Number,
    TC_154__Negative__Password_____Federal_Tax_ID_Number,
    TC_155__Negative__Customer_Last_Name_____Email_Address,
    TC_156__Negative__Customer_Last_Name_____Phone_Number,
    TC_157__Negative__Customer_Last_Name_____Username,
    TC_158__Negative__Customer_Last_Name_____Customer_Code_____Premises_Code,
    TC_159__Negative__Business_Name_____Email_Address,
    TC_160__Negative__Business_Name_____Phone_Number,
    TC_161__Negative__Business_Name_____Username,
    TC_162__Negative__Business_Name_____Customer_Code_____Premises_Code,
    TC_163__Negative__Email_Address_____Phone_Number,
    TC_164__Negative__Email_Address_____Username,
    TC_165__Negative__Email_Address_____Customer_Code_____Premises_Code,
    TC_166__Negative__Email_Address_____Federal_Tax_ID_Number,
    TC_167__Negative__Phone_Number_____Username,
    TC_168__Negative__Phone_Number_____Customer_Code_____Premises_Code,
    TC_169__Negative__Phone_Number_____Federal_Tax_ID_Number,
    TC_170__Negative__Username_____Customer_Code_____Premises_Code,
    TC_171__Negative__Username_____Federal_Tax_ID_Number,
    TC_172__Negative__Customer_Code_____Premises_Code_____Federal_Tax_ID_Number,
    TC_173__Negative__Too_Many_Matches,

    TC_174__Positive__Last_4_SSN_____Customer_Last_Name,
    TC_175__Positive__Last_4_SSN_____Email_Address,
    TC_176__Positive__Last_4_SSN_____Phone_Number,
    TC_177__Positive__Password_____Username,
    TC_178__Positive__Password_____Customer_Last_Name,
    TC_179__Positive__Password_____Business_Name,
    TC_180__Positive__Password_____Customer_Code_____Premises_Code,
    TC_181__Positive__Password_____Email_Address,
    TC_182__Positive__Password_____Phone_Number,
    TC_183__Positive__Business_Name_____Federal_Tax_ID,
    TC_184__Positive__Login_ID_Saved
}
