package com.gng.api.steps.meterSet.ServiceOrdersSteps.GetEligiblePlansAndOffers;

public enum GetEligiblePlansAndOffersApiLabel {

    get_eligible_plans_and_offers,
    get_eligible_plans_and_offers_mandatory,

    // VALIDATIONS (TC-006..009)
    MS_GE_MISSING_TRANSACTION_TYPE_TC_006,
    MS_GE_TRANSACTION_TYPE_MAX_LENGTH_TC_007,
    MS_GE_TRANSACTION_TYPE_INVALID_TC_008,
    MS_GE_AGLC_ACCOUNT_PROVIDED_TC_009,

    // RESIDENTIAL (TC-010..025) — add as needed from FTD-04
    MS_RS_FRAUD_ALERT_INVALID_SSN_TC_010,
    MS_RS_NO_MATCH_NO_CONFIRM_TC_011,
    MS_RS_NO_RECORD_FOUND_CONFIRM_PRP_ONLY_TC_012,
    MS_RS_NO_RECORD_FOUND_TC_013,
    MS_RS_VARIANT_TC_014,
    MS_RS_CREDIT_FREEZE_TC_015,
    MS_RS_DENIAL_DUE_TC_016,
    MS_RS_CUSTOMER_NO_AUTH_TC_017,
    MS_GE_TIER_1_NE_TC_018,
    MS_GE_TIER_2_NE_TC_019,
    MS_GE_TIER_9_NE_TC_020,
    MS_GE_RS_COMM_VS_150_TC_021,
    MS_GE_RS_ACN_LAND_BYPASS_CREDIT_TC_022,
    MS_GE_RS_INCL_TIER_5_TC_023,
    MS_RS_MULTIPLE_PREM_TC_024,
    MS_RS_CRDS_ENROLLMENT_CREDIT_CHECK_TC_025,

    MS_CM_NO_MATCH_INITIAL_TC_026,
    MS_CM_NO_MATCH_CONFIRM_RETURNS_PLANS_TC_027,
    MS_CM_NO_MATCH_WITH_BIN_CONFIRM_RETURNS_PLANS_TC_028,
    MS_CM_EXCELLENT_CREDIT_CGB_NOT_OFFERED_TC_029,
    MS_CM_CREDIT_SKIP_COM_BY_PASS_TC_030,
    MS_CM_CREDIT_MULTIPLE_CONFIRM_FALSE_NO_CGB_TC_031,
    MS_CM_NEW_EN_CREDIT_CHECK_NO_NO_PERMISSIONS_TC_032,
    MS_CM_CRDS_EN_CREDIT_CHECK_YES_COMM_DEP_PROSP_TC_033,
    MS_CM_CRDS_EN_CREDIT_CHECK_YES_BUSINESS_NAME_TC_034
}
