package com.gng.api.steps.turnOn.ServiceOrdersSteps.SaveEnrollment;

public enum SaveEnrollmentApiLabel {

    save_enrollment,
    save_enrollment_mandatory,

    // Request ID Types
    EMPTY_REQUEST_ID,
    DUPLICATE_REQUEST_ID,
    LONG_REQUEST_ID,


    //Invalid Customer Code Types
    MAX_LENGTH_CUSTOMER_CODE,
    NULL_CUSTOMER_CODE,
    DUPLICATE_CUSTOMER_CODE,
    SPECIAL_CHARS_CUSTOMER_CODE,
    //MAX_LENGTH_CUSTOMER_CODE,
    UNICODE_CHARS_CUSTOMER_CODE,


    // PremisesCode Types
    EMPTY_PREMISES_CODE,
    DUPLICATE_PREMISES_CODE,
    SPECIAL_CHARS_PREMISES_CODE,
    MAX_LENGTH_PREMISES_CODE,
    MIN_LENGTH_PREMISES_CODE,

    //Transaction ID Type
    MIN_LENGTH_TRANSACTION_ID,
    WHITESPACE_BETWEEN_TRANSACTION_ID,

    //transaction Type Cases
    EMPTY_TRANSACTION_TYPE,
    NUMERIC_TRANSACTION_TYPE,
    UPPERCASE_TRANSACTION_TYPE,
    ALPHANUMERIC_TRANSACTION_TYPE,
    LOWERCASE_TRANSACTION_TYPE,

    //plan Code
    NUMERIC_PLAN_CODE,
    SPECIAL_CHARS_PLAN_CODE,
    EMPTY_PLAN_CODE,
    UPPERCASE_PLAN_CODE,
    ALPHANUMERIC_PLAN_CODE,

    //LoginId
    MIN_LENGTH_LOGIN_ID,
    SPECIAL_CHARS_LOGIN_ID,
    EMPTY_LOGIN_ID,
    UPPERCASE_LOGIN_ID,
    ALPHANUMERIC_LOGIN_ID,
    MAX_LENGTH_LOGIN_ID,

    //enrollment Status
    MIN_LENGTH_ENROLLMENT_STATUS,
    SPECIAL_CHARS_ENROLLMENT_STATUS,
    EMPTY_ENROLLMENT_STATUS,
    LOWERCASE_ENROLLMENT_STATUS,
    MAX_LENGTH_ENROLLMENT_STATUS,
    WHITESPACE_CONTAINS_ENROLLMENT_STATUS,

    //billing plan
    MAX_LENGTH_BILLING_PLAN,
    SPECIAL_CHARS_BILLING_PLAN,
    EMPTY_BILLING_PLAN,
    LOWERCASE_BILLING_PLAN,

    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_NOTES_CE_TC_498,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_NOTES_PC_TC_499,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_NOTES_PC_TC_500A,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_NOTES_PC_TC_500B,

    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_CE_TC_423,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_DP_TC_425,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_PC_TC_431,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_PC_TC_432,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_SI_TC_433,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_DR_TC_435,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_PR_TC_438,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_PR_TC_439,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_RP_TC_442,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_RP_TC_443,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_RD_TC_446,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_BD_TC_452,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_SF_TC_454,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_PREV_SAVED_TC_424,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_PREV_SAVED_TC_426,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_PREV_SAVED_TC_426_1,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_PREV_SAVED_TC_427,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_PREV_SAVED_TC_428,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_PREV_SAVED_TC_434,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_PREV_SAVED_TC_436
}
