package com.gng.api.steps.turnOff.ServiceOrdersSteps.SaveUnenrollment;

public enum SaveUnenrollmentApiLabel {

    save_unenrollment,
    save_unenrollment_mandatory,

    // Request ID Types
    REQUEST_ID_EMPTY_NEGATIVE_TC106,
    REQUEST_ID_MAX_LENGTH_NEGATIVE_TC107,
    REQUEST_ID_DUPLICATE_NEGATIVE_TC108,

    // Login ID types
    LOGIN_ID_EMPTY_NEGATIVE_TC109,
    LOGIN_ID_MAX_LENGTH_NEGATIVE_TC110,
    LOGIN_ID_INVALID_ALPHA_NEGATIVE_TC111,
    LOGIN_ID_NOT_EXISTS_NEGATIVE_TC112,

    //TransactionType
    TRANSACTION_TYPE_EMPTY_NEGATIVE_TC113,
    TRANSACTION_TYPE_MAX_LENGTH_NEGATIVE_TC114,
    TRANSACTION_TYPE_INVALID_NEGATIVE_TC115,

    //Customer code
    CUSTOMER_CODE_EMPTY_NEGATIVE_TC116,
    CUSTOMER_CODE_MAX_LENGTH_NEGATIVE_TC117,
    CUSTOMER_CODE_NON_INT_NEGATIVE_TC118,
    CUSTOMER_CODE_NOT_EXISTS_NEGATIVE_TC119,

    //Premises code
    PREMISES_CODE_EMPTY_NEGATIVE_TC120,
    PREMISES_CODE_MAX_LENGTH_NEGATIVE_TC121,
    PREMISES_CODE_NOT_EXISTS_NEGATIVE_TC122,

    //Combination
    ACCOUNT_COMBINATION_INVALID_NEGATIVE_TC123,

    //AGLC AccountNumber
    AGLC_ACCOUNT_EMPTY_NEGATIVE_TC124,
    AGLC_ACCOUNT_MAX_LENGTH_NEGATIVE_TC125,

    //Forwarding AddressIs
    FWD_ADDRESS_EMPTY_NEGATIVE_TC129,
    FWD_ADDRESS_MAX_LENGTH_NEGATIVE_TC130,
    FWD_ADDRESS_INVALID_VALUE_NEGATIVE_TC131,

    // Forwarding Address Type
    FWD_ADDRESS_TYPE_EMPTY_NEGATIVE_TC132,
    FWD_ADDRESS_TYPE_MAX_LENGTH_NEGATIVE_TC133,
    FWD_ADDRESS_TYPE_INVALID_VALUE_NEGATIVE_TC134,

    // Forwarding Address Street Number
    FWD_ADD_STR_NUM_MAX_LENGTH_NEGATIVE_TC135,

    // Forwarding Address Street Pre-Direction
    FWD_ADD_STR_PRE_DIR_MAX_LENGTH_NEGATIVE_TC136,

    // Forwarding Address Street Name
    FWD_ADD_STR_NAME_EMPTY_NEGATIVE_TC137,
    FWD_ADD_STR_NAME_MAX_LENGTH_NEGATIVE_TC138,

    // Forwarding Address Street Suffix
    FWD_ADD_STR_SFX_MAX_LENGTH_NEGATIVE_TC139,

    // Forwarding Address Street Post Direction
    FWD_ADD_STR_POST_DIR_MAX_LENGTH_NEGATIVE_TC140,

    // Forwarding Address Unit Type
    FWD_ADD_UNIT_TYPE_MAX_LENGTH_NEGATIVE_TC141,

    // Forwarding Address Unit Number
    FWD_ADD_UNIT_NUM_MAX_LENGTH_NEGATIVE_TC142,

    // Forwarding Address Rural Route
    FWD_ADD_RURAL_ROUTE_MAX_LENGTH_NEGATIVE_TC143,

    // Forwarding Address PO Box
    FWD_ADD_PO_BOX_MAX_LENGTH_NEGATIVE_TC144,

    // Forwarding Address Line2
    FWD_ADD_LINE2_MAX_LENGTH_NEGATIVE_TC145,

    // Forwarding Address City
    FWD_ADD_CITY_EMPTY_NEGATIVE_TC146,
    FWD_ADD_CITY_MAX_LENGTH_NEGATIVE_TC147,

    // Forwarding Address State Code
    FWD_ADD_STATE_CODE_EMPTY_NEGATIVE_TC148,
    FWD_ADD_STATE_CODE_MAX_LENGTH_NEGATIVE_TC149,
    FWD_ADD_STATE_CODE_INVALID_NEGATIVE_TC150,

    // Forwarding Address Zip Code
    FWD_ADD_ZIP_CODE_EMPTY_NEGATIVE_TC151,
    FWD_ADD_ZIP_CODE_MAX_LENGTH_NEGATIVE_TC152,
    FWD_ADD_ZIP_CODE_INVALID_NEGATIVE_TC153,



    //POSITIVE TEST CONDITIONS
    SEASONAL_OR_HEAT_ONLY_TC207,
    MOVING_OUTSIDE_AGLC_TC208,
    OTHER_MILITARY_TC209,
    REAP_REALTOR_INSPECTION_TC210,
    OTHER_FINANCIAL_SITUATION_TC215,
    MOVING_NOT_STAYING_WITH_GNG_TC216,
    OTHER_REGULATED_PROVIDER_TC219,
    SEASONAL_OR_HEAT_ONLY_TC223,
    OTHER_DECEASED_TC222,
    OTHER_FINANCIAL_SITUATION_TC225,
    REAP_REALTOR_INSPECTION_TC227,
    MOVING_SERVICE_TRANSFER_TC228,
    MOVING_NOT_STAYING_WITH_GNG_TC229,
    MOVING_OUTSIDE_AGLC_TC230,
    MOVING_SERVICE_TRANSFER_TC232,
    MOVING_OUTSIDE_ETC_WAIVED_TC211,
    MOVING_SERVICE_TRANSFER_ETC_WAIVED_TC_213,
    OTHER_MILITARY_ETC_WAIVED_TC_217,
    MOVING_OUTSIDE_AGLC_ETC_WAIVED_TC_218,
    OTHER_DECEASED_ETC_WAIVED_TC_220,
    OTHER_REGULATED_PROVIDER_ETC_WAIVED_TC212,
    OTHER_RENOVATION_ELECTRIC_CONVERSION_TC221,
    OTHER_RENOVATION_ELECTRIC_CONVERSION_TC224,
    OTHER_MILITARY_ETC_WAIVED_TC_231,
    HOUSEHOLD_ACCOUNT_CHANGE_TC_214,
    MOVING_OUTSIDE_POOL_GROUP_TC_226,

    //Address types
    ADDRESS_TYPE_STREET,
    ADDRESS_TYPE_RURAL,
    ADDRESS_TYPE_POBOX,
    ADDRESS_TYPE_NOT_PRESENT,

    //Forwarding address to
    CURRENT_ADDRESS,
    NEW_ADDRESS
}
