package com.gng.api.steps.turnOff.ServiceOrdersSteps.SaveUnenrollment;

public enum SaveUnenrollmentApiLabel {

    save_unenrollment,
    save_unenrollment_mandatory,

    // Request ID Types
    REQUEST_ID_EMPTY_NEGATIVE_TC106,
    REQUEST_ID_MAX_LENGTH_NEGATIVE_TC107,
    REQUEST_ID_DUPLICATE_NEGATIVE_TC108,

    // Login ID types
    LOGIN_ID_EMPTY_NEGATIVE_TC109,
    LOGIN_ID_MAX_LENGTH_NEGATIVE_TC110,
    LOGIN_ID_INVALID_ALPHA_NEGATIVE_TC111,
    LOGIN_ID_NOT_EXISTS_NEGATIVE_TC112,

    //TransactionType
    TRANSACTION_TYPE_EMPTY_NEGATIVE_TC113,
    TRANSACTION_TYPE_MAX_LENGTH_NEGATIVE_TC114,
    TRANSACTION_TYPE_INVALID_NEGATIVE_TC115,

    //Customer code
    CUSTOMER_CODE_EMPTY_NEGATIVE_TC116,
    CUSTOMER_CODE_MAX_LENGTH_NEGATIVE_TC117,
    CUSTOMER_CODE_NON_INT_NEGATIVE_TC118,
    CUSTOMER_CODE_NOT_EXISTS_NEGATIVE_TC119,

    //Premises code
    PREMISES_CODE_EMPTY_NEGATIVE_TC120,
    PREMISES_CODE_MAX_LENGTH_NEGATIVE_TC121,
    PREMISES_CODE_NOT_EXISTS_NEGATIVE_TC122,

    //Combination
    ACCOUNT_COMBINATION_INVALID_NEGATIVE_TC123,

    //AGLC AccountNumber
    AGLC_ACCOUNT_EMPTY_NEGATIVE_TC124,
    AGLC_ACCOUNT_MAX_LENGTH_NEGATIVE_TC125,

    //Forwarding AddressIs
    FWD_ADDRESS_EMPTY_NEGATIVE_TC129,
    FWD_ADDRESS_MAX_LENGTH_NEGATIVE_TC130,
    FWD_ADDRESS_INVALID_VALUE_NEGATIVE_TC131,

    // Forwarding Address Type
    FWD_ADDRESS_TYPE_EMPTY_NEGATIVE_TC132,
    FWD_ADDRESS_TYPE_MAX_LENGTH_NEGATIVE_TC133,
    FWD_ADDRESS_TYPE_INVALID_VALUE_NEGATIVE_TC134,

    // Forwarding Address Street Number
    FWD_ADD_STR_NUM_MAX_LENGTH_NEGATIVE_TC135,

    // Forwarding Address Street Pre-Direction
    FWD_ADD_STR_PRE_DIR_MAX_LENGTH_NEGATIVE_TC136,

    // Forwarding Address Street Name
    FWD_ADD_STR_NAME_EMPTY_NEGATIVE_TC137,
    FWD_ADD_STR_NAME_MAX_LENGTH_NEGATIVE_TC138,

    // Forwarding Address Street Suffix
    FWD_ADD_STR_SFX_MAX_LENGTH_NEGATIVE_TC139,

    // Forwarding Address Street Post Direction
    FWD_ADD_STR_POST_DIR_MAX_LENGTH_NEGATIVE_TC140,

    // Forwarding Address Unit Type
    FWD_ADD_UNIT_TYPE_MAX_LENGTH_NEGATIVE_TC141,

    // Forwarding Address Unit Number
    FWD_ADD_UNIT_NUM_MAX_LENGTH_NEGATIVE_TC142,

    // Forwarding Address Rural Route
    FWD_ADD_RURAL_ROUTE_MAX_LENGTH_NEGATIVE_TC143,

    // Forwarding Address PO Box
    FWD_ADD_PO_BOX_MAX_LENGTH_NEGATIVE_TC144,

    // Forwarding Address Line2
    FWD_ADD_LINE2_MAX_LENGTH_NEGATIVE_TC145,

    // Forwarding Address City
    FWD_ADD_CITY_EMPTY_NEGATIVE_TC146,
    FWD_ADD_CITY_MAX_LENGTH_NEGATIVE_TC147,

    // Forwarding Address State Code
    FWD_ADD_STATE_CODE_EMPTY_NEGATIVE_TC148,
    FWD_ADD_STATE_CODE_MAX_LENGTH_NEGATIVE_TC149,
    FWD_ADD_STATE_CODE_INVALID_NEGATIVE_TC150,

    // Forwarding Address Zip Code
    FWD_ADD_ZIP_CODE_EMPTY_NEGATIVE_TC151,
    FWD_ADD_ZIP_CODE_MAX_LENGTH_NEGATIVE_TC152,
    FWD_ADD_ZIP_CODE_INVALID_NEGATIVE_TC153,
    FWD_ADD_ZIP_CODE_INVALID_FORMAT_NEGATIVE_TC154,

    // Turn Off Reason
    TURN_OFF_REASON_EMPTY_NEGATIVE_TC155,
    TURN_OFF_REASON_MAX_LENGTH_NEGATIVE_TC156,
    TURN_OFF_REASON_INVALID_NEGATIVE_TC157,

    // Turn Off Sub Reason
    TURN_OFF_SUB_REASON_EMPTY_NEGATIVE_TC158,
    TURN_OFF_SUB_REASON_MAX_LENGTH_NEGATIVE_TC159,
    TURN_OFF_SUB_REASON_EMPTY_MOVING_NEGATIVE_TC160,
    TURN_OFF_SUB_REASON_MAX_LENGTH_MOVING_NEGATIVE_TC161,

    // Turn Off Sub Reason – Invalid combinations
    TURN_OFF_SUB_REASON_INVALID_NO_ETC_TC162,
    TURN_OFF_SUB_REASON_INVALID_NO_ETC_TC163,
    TURN_OFF_SUB_REASON_INVALID_NO_ETC_TC164,
    TURN_OFF_SUB_REASON_INVALID_NO_ETC_TC165,
    TURN_OFF_SUB_REASON_INVALID_NO_ETC_TC166,
    TURN_OFF_SUB_REASON_INVALID_NO_ETC_TC167,
    TURN_OFF_SUB_REASON_INVALID_NO_ETC_TC168,
    TURN_OFF_SUB_REASON_INVALID_NO_ETC_TC169,

    TURN_OFF_SUB_REASON_INVALID_WITH_ETC_TC170,
    TURN_OFF_SUB_REASON_INVALID_WITH_ETC_TC171,
    TURN_OFF_SUB_REASON_INVALID_WITH_ETC_TC172,
    TURN_OFF_SUB_REASON_INVALID_WITH_ETC_TC173,
    TURN_OFF_SUB_REASON_INVALID_WITH_ETC_TC174,
    TURN_OFF_SUB_REASON_INVALID_WITH_ETC_TC175,
    TURN_OFF_SUB_REASON_INVALID_WITH_ETC_TC176,
    TURN_OFF_SUB_REASON_INVALID_WITH_ETC_TC177,

    TURN_OFF_SUB_REASON_INVALID_NO_ETC_TC178,
    TURN_OFF_SUB_REASON_INVALID_NO_ETC_TC179,
    TURN_OFF_SUB_REASON_INVALID_NO_ETC_TC180,
    TURN_OFF_SUB_REASON_INVALID_NO_ETC_TC181,
    TURN_OFF_SUB_REASON_INVALID_NO_ETC_TC182,
    TURN_OFF_SUB_REASON_INVALID_NO_ETC_TC183,
    TURN_OFF_SUB_REASON_INVALID_NO_ETC_TC184,

    TURN_OFF_SUB_REASON_INVALID_WITH_ETC_TC185,
    TURN_OFF_SUB_REASON_INVALID_WITH_ETC_TC186,
    TURN_OFF_SUB_REASON_INVALID_WITH_ETC_TC187,
    TURN_OFF_SUB_REASON_INVALID_WITH_ETC_TC188,
    TURN_OFF_SUB_REASON_INVALID_WITH_ETC_TC189,
    TURN_OFF_SUB_REASON_INVALID_WITH_ETC_TC190,
    TURN_OFF_SUB_REASON_INVALID_WITH_ETC_TC191,

    // Email
    EMAIL_MAX_LENGTH_NEGATIVE_TC192,
    EMAIL_INVALID_FORMAT_NEGATIVE_TC193,


    REQ_TURN_OFF_DATE_EMPTY_NEGATIVE_TC194,
    REQ_TURN_OFF_DATE_INVALID_FORMAT_NEGATIVE_TC195,

    // AGLC Service Order Number
    AGLC_SVC_ORDER_NUM_EMPTY_NEGATIVE_TC196,
    AGLC_SVC_ORDER_NUM_MAX_LENGTH_NEGATIVE_TC197,
    AGLC_SVC_ORDER_NUM_NON_NUMERIC_NEGATIVE_TC198,

    // ETC Exists
    ETC_EXISTS_INVALID_NEGATIVE_TC199,
    ETC_EXISTS_EMPTY_NEGATIVE_TC200,

    TURN_OFF_SUB_REASON_NOT_NULL_SEASONAL_ETC_TRUE_NEGATIVE_TC201,
    TURN_OFF_SUB_REASON_NOT_NULL_SEASONAL_ETC_FALSE_NEGATIVE_TC202,
    TURN_OFF_SUB_REASON_NOT_NULL_REAP_ETC_TRUE_NEGATIVE_TC203,
    TURN_OFF_SUB_REASON_NOT_NULL_REAP_ETC_FALSE_NEGATIVE_TC204,
    TURN_OFF_SUB_REASON_NOT_NULL_HOUSEHOLD_CHANGE_ETC_TRUE_NEGATIVE_TC205,
    TURN_OFF_SUB_REASON_NOT_NULL_HOUSEHOLD_CHANGE_ETC_FALSE_NEGATIVE_TC206,




    //POSITIVE TEST CONDITIONS
    SEASONAL_OR_HEAT_ONLY_TC207,
    MOVING_OUTSIDE_AGLC_TC208,
    OTHER_MILITARY_TC209,
    REAP_REALTOR_INSPECTION_TC210,
    OTHER_FINANCIAL_SITUATION_TC215,
    MOVING_NOT_STAYING_WITH_GNG_TC216,
    OTHER_REGULATED_PROVIDER_TC219,
    SEASONAL_OR_HEAT_ONLY_TC223,
    OTHER_DECEASED_TC222,
    OTHER_FINANCIAL_SITUATION_TC225,
    REAP_REALTOR_INSPECTION_TC227,
    MOVING_SERVICE_TRANSFER_TC228,
    MOVING_NOT_STAYING_WITH_GNG_TC229,
    MOVING_OUTSIDE_AGLC_TC230,
    MOVING_SERVICE_TRANSFER_TC232,
    MOVING_OUTSIDE_ETC_WAIVED_TC211,
    MOVING_SERVICE_TRANSFER_ETC_WAIVED_TC_213,
    OTHER_MILITARY_ETC_WAIVED_TC_217,
    MOVING_OUTSIDE_AGLC_ETC_WAIVED_TC_218,
    OTHER_DECEASED_ETC_WAIVED_TC_220,
    OTHER_REGULATED_PROVIDER_ETC_WAIVED_TC212,
    OTHER_RENOVATION_ELECTRIC_CONVERSION_TC221,
    OTHER_RENOVATION_ELECTRIC_CONVERSION_TC224,
    OTHER_MILITARY_ETC_WAIVED_TC_231,
    HOUSEHOLD_ACCOUNT_CHANGE_TC_214,
    MOVING_OUTSIDE_POOL_GROUP_TC_226,

    //Address types
    ADDRESS_TYPE_STREET,
    ADDRESS_TYPE_RURAL,
    ADDRESS_TYPE_POBOX,
    ADDRESS_TYPE_NOT_PRESENT,

    //Forwarding address to
    CURRENT_ADDRESS,
    NEW_ADDRESS
}
