package com.gng.api.steps.turnOff.ServiceOrdersSteps.SaveUnenrollment;

public enum SaveUnenrollmentApiLabel {

    save_unenrollment,
    save_unenrollment_mandatory,

    // Request ID Types
    EMPTY_REQUEST_ID,
    DUPLICATE_REQUEST_ID,
    LONG_REQUEST_ID,

    //POSITIVE TEST CONDITIONS
    SEASONAL_OR_HEAT_ONLY_TC207,
    MOVING_OUTSIDE_AGLC_TC208,
    OTHERS_MILITARY_TC209,
    REAP_REALTOR_INSPECTION_TC210,
    OTHER_FINANCIAL_SITUATION_TC215,
    MOVING_NOT_STAYING_WITH_GNG_TC216,
    OTHER_REGULATED_PROVIDER_TC219,
    SEASONAL_OR_HEAT_ONLY_TC223,
    OTHER_DECEASED_TC222,
    OTHER_FINANCIAL_SITUATION_TC225,
    REAP_REALTOR_INSPECTION_TC227,
    MOVING_SERVICE_TRANSFER_TC228,
    MOVING_NOT_STAYING_WITH_GNG_TC229,
    MOVING_OUTSIDE_AGLC_TC230,
    MOVING_SERVICE_TRANSFER_TC232
}
