package com.gng.api.steps.marketerSwitch.ServiceOrdersSteps.SaveEnrollment;

public enum SaveEnrollmentApiLabel {
    save_enrollment,
    save_enrollment_mandatory,

    SE_MRK_SW_MISSING_TRANSACTION_TYPE_TC_034,
    SE_MRK_SW_MAX_LENGTH_TRANSACTION_TYPE_TC_035,
    SE_MRK_SW_INVALID_TRANSACTION_TYPE_TC_036,
    SE_MRK_SW_SPLIT_CONN_FEE_TRUE_TC_037,
    SE_MRK_SW_ABLC_ACCOUNT_PROVIDED_TC_038,
    SE_MRK_SW_ABLC_SERVICE_PROVIDED_TC_039,
    SE_MRK_SW_MAX_LENGTH_CURRENT_MRK_CODE_TC_040,
    SE_MRK_SW_INVALID_CURRENT_MRK_CODE_TC_041,
    SE_MRK_SW_NOT_ALPHA_CURRENT_MRK_CODE_TC_042,

    //positive
    SE_MRK_SW_UPDATE_ENROLLMENT_GOOD_TC_43,
    SE_MRK_SW_DEPOSIT_PAID_NEW_FLOW_TC_44,
    SE_MRK_SW_PAYMENT_COMPLETE_PRP_PREVIOUS_TC_45,
    SE_MRK_SW_PAYMENT_COMPLETE_PGB_NEW_TC_46,
    SE_MRK_SW_SAVE_INCOMPLETE_SI_NEW_TC_47,
    SE_MRK_SW_DEPOSIT_REQUIRED_DR_PREVIOUS_TC_48,
    SE_MRK_SW_PREPAY_REQUIRED_PR_NEW_TC_49,
    SE_MRK_SW_PREPAY_REQUIRED_PR_PREVIOUS_TC_50,
    SE_MRK_SW_REFUSED_PREPAY_RP_NEW_TC_51,
    SE_MRK_SW_REFUSED_DEPOSIT_RD_NEW_TC_52,
    SE_MRK_SW_CANCEL_PREPAY_CP_PREVIOUS_TC_53,
    SE_MRK_SW_BUDGET_BILL_BD_NEW_TC_54,
    SE_MRK_SW_COMPLETE_ENROLLMENT_CE_NOTES_TC_55,

    // external
    GE_MRK_SW_RS_NEW_CC_YES_UC65_TC22,
    GE_MRK_SW_RS_CRDS_CC_YES_DEPOSIT_BILLED_VALUE110_TC24,
    GE_MRK_SW_CM_CRDS_CC_YES_PROMO_DEPOSIT_REQUIRED_VALUE210_CREDIT0_49_TC32,
    GE_MRK_SW_CM_CRDS_CC_YES_DEPOSIT_REQUIRED_BUSINESS_NAME_POPULATED_UC42_TC33
}
