package com.gng.api.steps.turnOn.GetDefaultPlansAndOffers;

public enum GetDefaultPlansAndOffersApiLabel {

    //type
    get_default_plans_and_offers,
    get_default_plans_and_offers_mandatory,

    //accountType
    RESIDENTIAL,
    COMMERCIAL,

    //promotionCodes
    DEALS,
    SAVE100,
    AAA,


    //enrollmentSources
    ALL_CONNECT,
    CIM_BUILDER_TURN_ON,
    CORRESPONDENCE,
    EMAIL,
    ENERGY_SHOP,
    FAX,
    GEORGIA_GAS_SAVINGS,
    GNG_HUB,
    MAIL,
    MOOVE_GURU,
    ONE_SOURCE,
    PHONE_CALL,
    VIV_INT,
    WEB,

    //test conditions
    GET_DEFAULT_PLANS_AND_OFFERS_TC_122,
    GET_DEFAULT_PLANS_AND_OFFERS_TC_124,
    GET_DEFAULT_PLANS_AND_OFFERS_TC_126,
    GET_DEFAULT_PLANS_AND_OFFERS_TC_127,
    GET_DEFAULT_PLANS_AND_OFFERS_TC_151,
    GET_DEFAULT_PLANS_AND_OFFERS_TC_151_1,
    GET_DEFAULT_PLANS_AND_OFFERS_TC_151_2,
    GET_DEFAULT_PLANS_AND_OFFERS_TC_151_3,
    GET_DEFAULT_PLANS_AND_OFFERS_TC_152,
    GET_DEFAULT_PLANS_AND_OFFERS_TC_152_1,
    GET_DEFAULT_PLANS_AND_OFFERS_TC_152_2,
    GET_DEFAULT_PLANS_AND_OFFERS_TC_153,
    GET_DEFAULT_PLANS_AND_OFFERS_TC_153_1,
    GET_DEFAULT_PLANS_AND_OFFERS_TC_153_2,
    GET_DEFAULT_PLANS_AND_OFFERS_TC_153_3,
    GET_DEFAULT_PLANS_AND_OFFERS_TC_153_4,
    GET_DEFAULT_PLANS_AND_OFFERS_TC_153_5,
    GET_DEFAULT_PLANS_AND_OFFERS_TC_153_6,
    GET_DEFAULT_PLANS_AND_OFFERS_TC_153_7,
    GET_DEFAULT_PLANS_AND_OFFERS_TC_153_8,
    GET_DEFAULT_PLANS_AND_OFFERS_TC_153_9,
    GET_DEFAULT_PLANS_AND_OFFERS_TC_153_10,
    GET_DEFAULT_PLANS_AND_OFFERS_TC_153_11,
    GET_DEFAULT_PLANS_AND_OFFERS_TC_153_12,
    GET_DEFAULT_PLANS_AND_OFFERS_TC_153_13,
    GET_DEFAULT_PLANS_AND_OFFERS_TC_153_14,
    GET_DEFAULT_PLANS_AND_OFFERS_TC_154
}
