package com.gng.api.steps.turnOn.ServiceOrdersSteps.GetEligiblePlansAndOffers;

public enum GetEligiblePlansAndOffersApiLabel {


    get_eligible_plans_and_offers,
    get_eligible_plans_and_offers_mandatory,

    //request ID
    NULL_REQUEST_ID,
    DUPLICATE_REQUEST_ID,
    SPECIAL_CHARS_REQUEST_ID,
    LONG_REQUEST_ID,
    UNICODE_CHARS_REQUEST_ID,

    //login ID
    INVALID_LOGIN_ID,
    NULL_LOGIN_ID,
    NON_NUMERIC_LOGIN_ID,
    ALPHANUMERIC_LOGIN_ID,
    MAX_LENGTH_LOGIN_ID,

    //transactionID
    NULL_TRANSACTION_ID_INCL_ENROLLMENT_STATE,
    NULL_TRANSACTION_ID_CRDS_ENROLLMENT_STATE,

    //customerCode
    NULL_CUSTOMER_CODE_INCL_ENROLLMENT_STATE,
    NULL_CUSTOMER_CODE_CRDS_ENROLLMENT_STATE,

    //premisesCode
    NULL_PREMISES_CODE_INCL_ENROLLMENT_STATE,
    NULL_PREMISES_CODE_CRDS_ENROLLMENT_STATE,
    VALID_PREMISES_CODE_NULL_ENROLLMENT_STATE,

    //transaction type
    EMPTY_TRANSACTION_TYPE,
    NUMERIC_TRANSACTION_TYPE,
    UPPERCASE_TRANSACTION_TYPE,
    LOWERCASE_TRANSACTION_TYPE,
    ALPHANUMERIC_TRANSACTION_TYPE,
    WHITESPACE_CONTAINS_TRANSACTION_TYPE,
    MAX_LENGTH_TRANSACTION_TYPE,

    //customer Type
    EMPTY_CUSTOMER_TYPE,
    MIN_LENGTH_CUSTOMER_TYPE,
    NUMERIC_CUSTOMER_TYPE,
    SPL_CHAR_CUSTOMER_TYPE,
    MAX_LENGTH_CUSTOMER_TYPE,

    //enrollment Sources
    EMPTY_ENROLLMENT_SOURCES,
    NUMERIC_ENROLLMENT_SOURCES,
    SPL_CHAR_ENROLLMENT_SOURCES,
    MAX_LENGTH_ENROLLMENT_SOURCES,

    //customer last name
    EMPTY_CUSTOMER_LAST_NAME,
    LOWERCASE_CUSTOMER_LAST_NAME,
    SPL_CHAR_CUSTOMER_LAST_NAME,
    MAX_LENGTH_CUSTOMER_LAST_NAME,
    NUMERIC_CUSTOMER_LAST_NAME,

    //customer first name
    EMPTY_CUSTOMER_FIRST_NAME,


    //credit check
    EMPTY_CREDIT_CHECK_OPTION,
    INVALID_CREDIT_CHECK_OPTION,
    MAX_LENGTH_CREDIT_CHECK_OPTION,


    //TenantLandlord
    EMPTY_TENANT_LANDLORD,
    SPL_CHAR_TENANT_LANDLORD,
    MAX_LENGTH_TENANT_LANDLORD,
    LOWERCASE_TENANT_LANDLORD,
    NUMERIC_TENANT_LANDLORD,


    //AcnStatusIndicator
    EMPTY_ACN_STATUS_INDICATOR_WITH_TENANT_LANDLORD,
    INVALID_ACN_STATUS_INDICATOR_VALUE_NOT_PRESENT_IN_TABLE,
    MAX_LENGTH_ACN_STATUS_INDICATOR,
    VALID_ACN_STATUS_INDICATOR_WITH_MAX_LENGTH_TENANT_LANDLORD,
    VALID_ACN_STATUS_INDICATOR_WITH_NULL_TENANT_LANDLORD,
    VALID_ACN_STATUS_INDICATOR_VALID_TENANT_LANDLORD_L_WITH_INVALID_USER_ROLE,
    VALID_ACN_STATUS_INDICATOR_VALID_TENANT_LANDLORD_T_WITH_INVALID_USER_ROLE,
    NULL_ACN_STATUS_INDICATOR_VALID_TENANT_LANDLORD_L_WITH_INVALID_USER_ROLE,
    NULL_ACN_STATUS_INDICATOR_VALID_TENANT_LANDLORD_T_WITH_INVALID_USER_ROLE,

    //customerPEWCPrefernce
    CUSTOMER_PEWC_PREFRENCES_VALUE_GOOD_WITH_OTHER_PARAM_NULL,
    CUSTOMER_PEWC_PREFRENCES_VALUE_TRUE_WITH_OTHER_PARAM_NULL,


    //testCondition
    NULL_AUTHORIZED_BY_237,

    //referralCode
    MAX_REFERRAL_CODE,
    NONNUMERIC_REFERRAL_CODE,
    ALPHANUMERIC_REFERRAL_CODE,
    VALID_REFERRAL_CODE_WITH_MISSING_MARKETING_CODE,
    TRANSACTION_MANAGER_DIFF_REQUEST_ID,
    TRANSACTION_MANAGER_WITH_REQUEST_ID,


    //PremisesStreetNumber
    MAX_PREMISES_STREET_NUMBER,

    //premisesStreetPreDirection
    MAX_PREMISES_STREET_PRE_DIRECTION,
    INVALID_PREMISES_STREET_PRE_DIRECTION_EQUAL_TO_TWO,

    MAX_PREMISES_STREET_NAME,
    NULL_PREMISES_STREET_NAME,
    //PremisesStreetSuffix
    MAX_PREMISES_STREET_SUFFIX,
    INVALID_PREMISES_STREET_SUFFIX,

    //PremisesStreetPostDirection
    MAX_PREMISES_STREET_POST_DIRECTION,
    INVALID_PREMISES_STREET_POST_DIRECTION_EQUAL_TO_TWO,

    //premisesUnitType
    MAX_PREMISES_UNIT_TYPE,
    INVALID_PREMISES_UNIT_TYPE,

    //premisesUnitNumber
    MAX_PREMISES_UNIT_NUMBER,

    //premisesCity
    MAX_PREMISES_CITY,
    NULL_PREMISES_CITY,

    //premises state code
    EMPTY_PREMISES_STATE_CODE,
    MAX_LENGTH_PREMISES_STATE_CODE,
    INVALID_PREMISES_STATE_CODE_EQUAL_TO_TWO,

    //premises zip code
    EMPTY_PREMISES_ZIP_CODE,
    MAX_LENGTH_PREMISES_ZIP_CODE,
    INVALID_PREMISES_ZIP_FORMAT_CODE,
    NUMERIC_PREMISES_ZIP_CODE,
    LOWERCASE_PREMISES_ZIP_CODE,
    INVALID_PREMISES_ZIP_CODE_RANDOM_STRING,

    //premises County Code
    EMPTY_PREMISES_COUNTY_CODE,
    MIN_LENGTH_PREMISES_COUNTY_CODE,
    ALPHANUMERIC_PREMISES_COUNTY_CODE,


    //SeparateBillingAddress
    EMPTY_SEPARATE_BILLING_ADDRESS,
    MIN_LENGTH_SEPARATE_BILLING_ADDRESS,
    SEPARATE_BILLING_ADDRESS_BILLING_ADD_TYPE_PROVIDED,
    VALID_SEPARATE_BILLING_ADDRESS_WITH_INVALID_BILLING_STREET_NUMBER,
    SEPARATE_BILLING_ADDRESS_BILLING_ADD_TYPE_MISSING,
    SEPARATE_BILLING_ADDRESS_WITH_INVALID_BILLING_ADD_TYPE,
    INVALID_SEPARATE_BILLING_ADDRESS_WITH_VALID_BILLING_ADD_TYPE,
    VALID_BILLING_ADDRESS_TYPE_WITH_INVALID_BILLING_STREET_NUMBER,
    VALID_BILLING_ADDRESS_TYPE_WITH_MAX_LENGTH_BILLING_STREET_PRE_DIRECTION,
    VALID_BILLING_ADDRESS_TYPE_WITH_INVALID_BILLING_STREET_PRE_DIRECTION,
    VALID_BILLING_ADDRESS_TYPE_WITH_MAX_LENGTH_BILLING_STREET_SUFFIX,
    VALID_BILLING_ADDRESS_TYPE_WITH_INVALID_BILLING_STREET_SUFFIX,
    VALID_BILLING_ADDRESS_TYPE_WITH_MAX_LENGTH_BILLING_STREET_POST_DIRECTION,
    VALID_BILLING_ADDRESS_TYPE_WITH_INVALID_BILLING_STREET_POST_DIRECTION,
    VALID_BILLING_ADDRESS_TYPE_WITH_INVALID_BILLING_UNIT_TYPE,
    VALID_BILLING_ADDRESS_TYPE_WITH_MAX_LENGTH_BILLING_UNIT_TYPE,
    VALID_BILLING_ADDRESS_TYPE_WITH_MAX_LENGTH_BILLING_UNIT_NUMBER,
    VALID_BILLING_ADDRESS_TYPE_WITH_MAX_LENGTH_BILLING_RURAL_ROUTE,
    VALID_BILLING_ADDRESS_TYPE_WITH_EMPTY_BILLING_RURAL_ROUTE,
    VALID_BILLING_ADDRESS_TYPE_WITH_MAX_LENGTH_BILLING_RURAL_ROUTE_NUMBER,
    VALID_BILLING_ADDRESS_TYPE_WITH_NULL_BILLING_RURAL_ROUTE_NUMBER,
    VALID_BILLING_ADDRESS_TYPE_WITH_MAX_LENGTH_BILLING_PO_BOX,
    VALID_BILLING_ADDRESS_TYPE_WITH_NULL_BILLING_PO_BOX,
    VALID_BILLING_ADDRESS_TYPE_WITH_MAX_LENGTH_BILLING_ADDRESS_LINE2,
    VALID_BILLING_ADDRESS_TYPE_WITH_MAX_LENGTH_BILLING_ADDRESS_LINE2_WITH_BILLING_RURAL_ROUTE,
    VALID_BILLING_ADDRESS_TYPE_WITH_MAX_LENGTH_BILLING_ADDRESS_LINE2_WITH_BILLING_PO_BOX,
    VALID_BILLING_ADDRESS_TYPE_S_WITH_MAX_LENGTH_BILLING_CITY,
    VALID_BILLING_ADDRESS_TYPE_R_WITH_MAX_LENGTH_BILLING_CITY_WITH_BILLING_RURAL_ROUTE,
    VALID_BILLING_ADDRESS_TYPE_P_WITH_MAX_LENGTH_BILLING_CITY_WITH_BILLING_PO_BOX,
    VALID_BILLING_ADDRESS_TYPE_S_WITH_MAX_LENGTH_BILLING_STATE_CODE_WITH_BILLING_PO_BOX_279b,
    VALID_BILLING_ADDRESS_TYPE_R_WITH_MAX_LENGTH_BILLING_STATE_CODE_WITH_BILLING_RURAL_ROUTE,
    VALID_BILLING_ADDRESS_TYPE_P_WITH_MAX_LENGTH_BILLING_STATE_CODE_WITH_BILLING_PO_BOX,
    VALID_BILLING_ADDRESS_TYPE_S_WITH_INVALID_BILLING_STATE_CODE_NOT_PRESENT_IN_TABLE,
    VALID_BILLING_ADDRESS_TYPE_R_WITH_INVALID_BILLING_STATE_CODE_NOT_PRESENT_IN_TABLE,
    VALID_BILLING_ADDRESS_TYPE_P_WITH_INVALID_BILLING_STATE_CODE_NOT_PRESENT_IN_TABLE,
    VALID_BILLING_ADDRESS_TYPE_S_WITH_INVALID_BILLING_ZIP_CODE,
    VALID_BILLING_ADDRESS_TYPE_S_WITH_MIN_LENGTH_BILLING_ZIP_CODE,
    VALID_BILLING_ADDRESS_TYPE_R_WITH_MIN_LENGTH_BILLING_ZIP_CODE,
    VALID_BILLING_ADDRESS_TYPE_R_WITH_INVALID_BILLING_ZIP_CODE,
    VALID_BILLING_ADDRESS_TYPE_P_WITH_INVALID_BILLING_ZIP_CODE,
    VALID_BILLING_ADDRESS_TYPE_P_WITH_MIN_LENGTH_BILLING_ZIP_CODE,
    VALID_BILLING_ADDRESS_TYPE_S_WITH_BILLING_ZIP_CODE_MISSING_281c,
    VALID_BILLING_ADDRESS_TYPE_P_WITH_BILLING_ZIP_CODE_MISSING_281e,
    VALID_BILLING_ADDRESS_TYPE_S_WITH_MAX_LENGTH_BILLING_COUNTY_CODE,
    VALID_BILLING_ADDRESS_TYPE_R_WITH_MAX_LENGTH_BILLING_COUNTY_CODE_BILLING_RURAL_ROUTE,
    VALID_BILLING_ADDRESS_TYPE_P_WITH_MAX_LENGTH_BILLING_COUNTY_CODE_WITH_BILLING_PO_BOX,
    VALID_BILLING_ADDRESS_TYPE_S_WITH_BILLING_COUNTY_CODE_NOT_PRESENT_IN_TABLE,
    VALID_BILLING_ADDRESS_TYPE_R_WITH_BILLING_COUNTY_CODE_NOT_PRESENT_IN_TABLE,
    VALID_BILLING_ADDRESS_TYPE_P_WITH_BILLING_COUNTY_CODE_NOT_PRESENT_IN_TABLE_WITH_BILLING_PO_BOX,
    NULL_WORK_PHONE_NUMBER_WITH_VALID_WORK_PHONE_TYPE,
    ALPHANUMERIC_WORK_PHONE_NUMBER,
    MIN_LENGTH_WORK_PHONE_NUMBER,
    NULL_WORK_PHONE_TYPE_WITH_VALID_WORK_PHONE_NUMBER,
    MAX_LENGTH_WORK_EXTENSION_TYPE,
    WORK_PHONE_TYPE_PROVIDED_MAX_1_CHAR,
    INVALID_WORK_PHONE_TYPE_VALUE,
    MIN_LENGTH_HOME_PHONE_NUMBER,
    ALPHANUMERIC_HOME_PHONE_NUMBER,
    NULL_HOME_PHONE_NUMBER_WITH_VALID_HOME_PHONE_TYPE,
    NULL_HOME_PHONE_TYPE_WITH_VALID_HOME_PHONE_NUMBER_294,
    HOME_PHONE_TYPE_PROVIDED_MAX_1_CHAR_296,
    INVALID_HOME_PHONE_TYPE_VALUE_297,

    MAX_LENGTH_INITIAL_CREDIT_CHECK_CUSTOMER_CODE_313,
    NONNUMERIC_INITIAL_CREDIT_CHECK_CUSTOMER_CODE_314,
    EMPTY_INITIAL_CREDIT_CHECK_CUSTOMER_CODE_WITH_CREDIT_CHECK_OPTION_315,
    INVALID_INITIAL_CREDIT_CHECK_CUSTOMER_CODE_NOT_PRESENT_IN_TABLE_316,
    INVALID_INITIAL_CREDIT_CHECK_CUSTOMER_CODE_WITHOUT_CREDIT_SCORE_317,

    //POSITIVE TEST CONDITIONS
    GET_ELIGIBLE_PLANS_AND_OFFERS_TC_318,
    GET_ELIGIBLE_PLANS_AND_OFFERS_TC_319,
    GET_ELIGIBLE_PLANS_AND_OFFERS_TC_320,
    GET_ELIGIBLE_PLANS_AND_OFFERS_TC_321,
    GET_ELIGIBLE_PLANS_AND_OFFERS_TC_322,
    GET_ELIGIBLE_PLANS_AND_OFFERS_TC_323,
    GET_ELIGIBLE_PLANS_AND_OFFERS_TC_324,
    GET_ELIGIBLE_PLANS_AND_OFFERS_TC_325,
    GET_ELIGIBLE_PLANS_AND_OFFERS_TC_326,
    GET_ELIGIBLE_PLANS_AND_OFFERS_TC_327,
    GET_ELIGIBLE_PLANS_AND_OFFERS_TC_328,

    GET_ELIGIBLE_PLANS_AND_OFFERS_TC_329,
    GET_ELIGIBLE_PLANS_AND_OFFERS_TC_330,
    GET_ELIGIBLE_PLANS_AND_OFFERS_TC_331,
    GET_ELIGIBLE_PLANS_AND_OFFERS_TC_332,
    GET_ELIGIBLE_PLANS_AND_OFFERS_TC_333,
    GET_ELIGIBLE_PLANS_AND_OFFERS_TC_334,
    GET_ELIGIBLE_PLANS_AND_OFFERS_TC_335,
    GET_ELIGIBLE_PLANS_AND_OFFERS_TC_336,
    GET_ELIGIBLE_PLANS_AND_OFFERS_TC_337,
    GET_ELIGIBLE_PLANS_AND_OFFERS_TC_338,
    GET_ELIGIBLE_PLANS_AND_OFFERS_TC_338a,
    GET_ELIGIBLE_PLANS_AND_OFFERS_TC_338e,

    //EXTERNAL
    GET_PREPAY_PLANS_REQUOTE_POSITIVE_TC_456,
    GET_PREPAY_PLANS_REQUOTE_POSITIVE_TC_471,
    GET_PREPAY_PLANS_REQUOTE_POSITIVE_TC_472,
    GET_PREPAY_PLANS_REQUOTE_NEGATIVE_TC_469,
    GET_PREPAY_PLANS_REQUOTE_EXISTING_QUOTE_NOT_EXPIRED_NEGATIVE_TC_470,
    GET_PREPAY_PLANS_REQUOTE_PRP_ENROLLED_NEGATIVE_TC_471,
    SAVE_ENROLLMENT_INVALID_ENROLLMENT_STATUS_NO_MATCH_TC401,
    SAVE_ENROLLMENT_INVALID_ENROLLMENT_STATUS_MISSING_CONFIRMATION_TC402,
    SAVE_ENROLLMENT_INVALID_PAYMENT_CONFIRMATION_NUM_MAX_LENGTH_TC403,

    SAVE_ENROLLMENT_INVALID_PROMOTION_CODE_NO_MATCH_TC398,
    SAVE_ENROLLMENT_INVALID_BILLING_PLAN_EMPTY_TC404,
    SAVE_ENROLLMENT_INVALID_VALUE_BILLING_PLAN_TC406,
    SAVE_ENROLLMENT_INVALID_VALUE_BILLING_PLAN_PREPAY_TC406a,
    SAVE_ENROLLMENT_INVALID_BILLING_PLAN_EMPTY_BUDGET_AMOUNT_TC407,
    SAVE_ENROLLMENT_INVALID_BUDGET_AMOUNT_MAX_LENGTH_TC408,
    SAVE_ENROLLMENT_INVALID_VALUE_BUDGET_AMOUNT_TC409,
    SAVE_ENROLLMENT_INVALID_SERVICE_DATE_EMPTY_TC410,
    SAVE_ENROLLMENT_INVALID_SERVICE_DATE_FORMAT_TC411,
    SAVE_ENROLLMENT_INVALID_SERVICE_DATE_FORMAT_TC411a,
    SAVE_ENROLLMENT_INVALID_SSP_EMPTY_TC412,
    SAVE_ENROLLMENT_INVALID_SSP_RESULT_MAX_LENGTH_TC413,
    SAVE_ENROLLMENT_INVALID_SSP_RESULT_VALUE_TC414,
    SAVE_ENROLLMENT_INVALID_SSP_SPLIT_FEE_EMPTY_TC415,
    SAVE_ENROLLMENT_INVALID_SSP_SPLIT_FEE_VALUE_TC416,
    SAVE_ENROLLMENT_INVALID_SPLIT_FEE_VALUE_TC417a,
    SAVE_ENROLLMENT_INVALID_AGLC_ACCOUNT_EMPTY_TC418,
    SAVE_ENROLLMENT_INVALID_AGLC_ACCOUNT_MAX_LENGTH_TC419,
    SAVE_ENROLLMENT_INVALID_AGLC_SERVICE_ORDER_EMPTY_TC420,
    SAVE_ENROLLMENT_INVALID_AGLC_SERVICE_ORDER_MAX_LENGTH_TC421,
    SAVE_ENROLLMENT_INVALID_NOTES_MAX_LENGTH_TC422,
    SAVE_ENROLLMENT_INVALID_SSP_PC_MAX_LENGTH_TC422a,
    SAVE_ENROLLMENT_INVALID_SSP_PC_VALUE_TC422b,

    //CREDIT CHECK TYPES
    CREDIT_CHECK_YES,
    CREDIT_CHECK_NO,
    CREDIT_CHECK_SERVICE_TRANSFER,
    CREDIT_CHECK_COMMERCIAL_CHECK_REQUIRED,
    CREDIT_CHECK_MULTIPLE_PREMISES,
    CREDIT_CHECK_NOT_REQUIRED,
    CREDIT_CHECK_ACN_LANDLORD,



    COMMERCIAL_CREDIT_CHECK_YES_TC_339,
    COMMERCIAL_CREDIT_CHECK_YES_NEW_ENROLLMENT_TC_340,
    COMMERCIAL_CREDIT_CHECK_SKIP_NEW_ENROLLMENT_TC_341,
    COMMERCIAL_CREDIT_CHECK_YES_NEW_ENROLLMENT_TC_342,
    COMMERCIAL_CREDIT_CHECK_YES_NEW_ENROLLMENT_TC_343,
    COMMERCIAL_CREDIT_CHECK_SERV_TRANSFER_NEW_ENROLLMENT_TC_344,
    COMMERCIAL_CREDIT_CHECK_MULT_NEW_ENROLLMENT_TC_345,
    COMMERCIAL_CREDIT_CHECK_YES_NEW_ENROLLMENT_TC_346,
    COMMERCIAL_CREDIT_CHECK_YES_NEW_ENROLLMENT_TC_347,
    COMMERCIAL_CREDIT_CHECK_YES_NEW_ENROLLMENT_TC_348,
    COMMERCIAL_CREDIT_CHECK_YES_NEW_ENROLLMENT_TC_349,
    COMMERCIAL_CREDIT_CHECK_YES_INCL_ENROLLMENT_TC_350,
    COMMERCIAL_CREDIT_CHECK_YES_CRDS_ENROLLMENT_TC_350B,
    COMMERCIAL_CREDIT_CHECK_YES_CRDS_ENROLLMENT_TC_350E,

    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_CE_NEW_TC_423,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_CE_PREVIOUSLY_SAVED_TC_424,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_NOTES_CE_TC_498,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_NOTES_PC_TC_499,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_NOTES_PC_TC_500A,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_NOTES_PC_TC_500B,

    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_CE_TC_423,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_DP_TC_425,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_PC_TC_431,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_PC_TC_432,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_SI_TC_433,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_DR_TC_435,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_PR_TC_438,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_PR_TC_439,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_RP_TC_442,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_RP_TC_443,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_RD_TC_446,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_BD_TC_452,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_SF_TC_454,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_PREV_SAVED_TC_424,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_PREV_SAVED_TC_426,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_PREV_SAVED_TC_426_1,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_PREV_SAVED_TC_427,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_PREV_SAVED_TC_428,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_PREV_SAVED_TC_434,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_PREV_SAVED_TC_436,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_PREV_SAVED_TC_440,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_SF_TC_501,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_CE_TC_502,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_SI_TC_503,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_SI_TC_504,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_CE_TC_505,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_PREV_SAVED_TC_506,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_PREV_SAVED_TC_507,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_SF_TC_508,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_SF_TC_509,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_SF_TC_510,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_SF_TC_511,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_SF_TC_512,

    SSP_TRUE_NOT_ALLOWED_FOR_ACN_TC_476,
    SSP_FALSE_ALLOWED_FOR_ACN_TC_477,
    SSP_VALIDATION_CUSTOMER_CODE_MISSING_TC_478,
    SSP_VALIDATION_CUSTOMER_CODE_MISSING_TC_479,
    SSP_VALIDATION_CUSTOMER_CODE_MISSING_TC_480,
    SSP_VALIDATION_CUSTOMER_CODE_MISSING_TC_481,
    SSP_VALIDATION_CUSTOMER_CODE_MISSING_TC_482,
    SSP_VALIDATION_CUSTOMER_CODE_MISSING_TC_482_2,
    SSP_VALIDATION_CUSTOMER_CODE_MISSING_TC_483,
    SSP_VALIDATION_CUSTOMER_CODE_MISSING_TC_483_2,
    SSP_VALIDATION_PREMISES_CODE_MISSING_TC_484,
    SSP_VALIDATION_PREMISES_CODE_MISSING_TC_485,
    SSP_VALIDATION_CUSTOMER_CODE_MISSING_TC_486,
    SSP_VALIDATION_CUSTOMER_CODE_MISSING_TC_487,
    SSP_VALIDATION_PREMISES_CODE_MISSING_TC_488,
    SSP_VALIDATION_PREMISES_CODE_MISSING_TC_488_2,
    SSP_VALIDATION_SSP_PARTICIPANT_CODE_MISSING_TC_490,
    SSP_VALIDATION_SSP_PARTICIPANT_CODE_MISSING_TC_491,
    SSP_VALIDATION_SSP_PARTICIPANT_CODE_MISSING_TC_492,
    SSP_VALIDATION_SSP_PARTICIPANT_CODE_MISSING_TC_493,
    SSP_VALIDATION_SSP_PARTICIPANT_CODE_MISSING_TC_494,
    SSP_VALIDATION_SSP_PARTICIPANT_CODE_MISSING_TC_494_2,
    SSP_VALIDATION_SSP_PARTICIPANT_CODE_MISSING_TC_495,
    SSP_VALIDATION_SSP_PARTICIPANT_CODE_MISSING_TC_495_2,
    SSP_VALIDATION_PAYMENT_CONFIRMATION_NUMBER_MISSING_TC_496,
    SSP_VALIDATION_INVALID_SSP_RESULT_TC_497B,
    SSP_VALIDATION_INVALID_SSP_CODE_TC_497C,
    GET_PREPAY_PLANS_REQUOTE_AND_OFFERS_SAVE_ENROLLMENT_PREV_SAVED_TC_429,
    GET_PREPAY_PLANS_REQUOTE_AND_OFFERS_SAVE_ENROLLMENT_PREV_SAVED_TC_430,
    SSP_VALIDATION_PREMISES_CODE_MISSING_TC_492,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_PREV_SAVED_TC_437,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_PREV_SAVED_TC_441,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_PREV_SAVED_TC_444,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_PREV_SAVED_TC_445,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_PREV_SAVED_TC_447,
    GET_PREPAY_PLANS_REQUOTE_AND_OFFERS_SAVE_ENROLLMENT_PREV_SAVED_TC_448,
    GET_PREPAY_PLANS_REQUOTE_AND_OFFERS_SAVE_ENROLLMENT_PREV_SAVED_TC_449,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_PREV_SAVED_TC_450,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_PREV_SAVED_TC_451,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_PREV_SAVED_TC_453,
    GET_ELIGIBLE_PLANS_AND_OFFERS_SAVE_ENROLLMENT_PREV_SAVED_SSP_TC_455
}
